### ISSUE TITLE
Option to edit created issue

### ISSUE THREAD

**Issue by Sachpat** [hub4j/github-api#1000]
Hi,

Currently I don't see a way to edit or update the already created issue as the editIssue() method in GHIssue is private and there is no other method to access it also. Please provide a  way to edit the issues or if I am missing something, can you please let me know if there is another way to do it? 

Kind regards,
Sachin

**Comment by bitwiseman** [comment]
@Sachpat 
`editIssue` is called by other methods such as `setMilestone()`. Use the other methods. 

https://github.com/hub4j/github-api/blob/5377d0dd184910dd0923576d2a2a9eeaf3283976/src/main/java/org/kohsuke/github/GHIssue.java#L295-L300
