### ISSUE TITLE
Add GHIssueQueryBuilder to allow better filtering of issue queries

### ISSUE THREAD

**Issue by blacelle** [hub4j/github-api#1025]
**Describe the feature**
GitHub API  enables multiple search criteria: https://docs.github.com/en/rest/reference/issues#list-repository-issues (e.g. assignee, creator, labels). 

How, I can't see how one can take advantage of these parameters through the library API?

**Additional context**
I might have crafted manually a call similar to 

```
    /**
     * Lists up all the issues in this repository.
     *
     * @param state
     *            the state
     * @return the paged iterable
     */
    public PagedIterable<GHIssue> listIssues(final GHIssueState state) {
        return root.createRequest()
                .with("state", state)
                .withUrlPath(getApiTailUrl("issues"))
                .toIterable(GHIssue[].class, item -> item.wrap(this));
    }
```

but it seems not trivial to get a reference to the root variable inside GHRepository.

Thanks

**Comment by bitwiseman** [comment]
You're right. We have a [`GHPullRequestQueryBuilder`](https://github.com/hub4j/github-api/blob/master/src/main/java/org/kohsuke/github/GHPullRequestQueryBuilder.java) but not a `GHIssueQueryBuilder`.  You could use the `GHPullRequestQueryBuilder` as a template or even move to having a `GHIssueQueryBuilder` as a base class for `GHPullRequestQueryBuilder`.
