### ISSUE TITLE
Add workflow_run and workflow_dispatch events

### ISSUE THREAD

**Issue by jeffmaury** [hub4j/github-api#1037]
**Describe the bug**

Add these 2 new events

**Comment by bitwiseman** [comment]
They exist in https://github.com/hub4j/github-api/blob/master/src/main/java/org/kohsuke/github/GHEvent.java but they need to be added to https://github.com/hub4j/github-api/blob/master/src/main/java/org/kohsuke/github/GHEventPayload.java

**Comment by gsmet** [comment]
@bitwiseman am I right if I say that all the Workflows API is currently not exposed? I.e. https://docs.github.com/en/rest/reference/actions#workflows

**Comment by bitwiseman** [comment]
@gsmet  
You are correct.  There is no `GHWorkflow`, `GHWorkflowJob`, or `GHWorkflowRun`.  Are you interested in adding them?

**Comment by gsmet** [comment]
I would be even more interested in just using them ;).

But yeah, we need at least part of this API for Quarkus. I can't promise we will implement all of it though as we mostly need the `GHWorkflowRun`. But in any case, that will start this effort.

We will keep you posted.

**Comment by gsmet** [comment]
FWIW, I'm making good progress in adding `GHWorkflow` and `GHWorkflowRun` which are the ones I need. Not sure if it will be possible to reuse them for the payloads though.

**Comment by bitwiseman** [comment]
@gsmet 
Progress: awesome!  The sooner you create a PR the better. Early feedback, etc. 
Not possible to reuse: Okay. I'm not sure I understand, but do what you think is reasonable and we'll iterate if needed.

**Comment by gsmet** [comment]
Yeah, I will open a PR once I have a reasonable certainty that things are working properly, I'm still working on a first iteration of the tests.

As for the payloads, it's just that I didn't have a look and wasn't sure my work would apply to Jeff's initial request but I had a look yesterday and it looks like things could be reused quite easily.
