### ISSUE TITLE
Undeprecate Reaction API

### ISSUE THREAD

**Issue by gastaldi** [hub4j/github-api#1048]
The `Reactable` implementations are really useful to trigger a reaction on an issue/PR comment, not sure why it was originally added as deprecated

**Comment by gastaldi** [comment]
May be related to https://github.com/hub4j/github-api/issues/1003?

**Comment by bitwiseman** [comment]
@gastaldi Yes. The Reaction API is in preview from GitHub. As such, there is no guarantee that the API won't change, so we mark it as deprecated so that users don't mistakenly think the API is stable.  Use preview APIs at your own risk.
