### ISSUE TITLE
GHIssue.addLabels and removeLabels() should return `List<GHLabel>` not `void`

### ISSUE THREAD

**Issue by bitwiseman** [hub4j/github-api#1050]
In #1049, @gsmet mentioned that on `GHIssue`, `addLabels()` and `removeLabels()` are using the wrong endpoint.  They should be using [this one](https://docs.github.com/en/rest/reference/issues#add-labels-to-an-issue) with either `POST` or `DELETE` method.  As a further point, those endpoints return the resulting list of labels, but the methods return `void`.   

The may be doable using bridge methods, but if not it is a breaking change.

**Comment by bitwiseman** [comment]
Turns out `void` bridge methods exist and they work.

https://github.com/hub4j/github-api/blob/6d86cfb4f60642ccfc3ad943eeb472e33e2ff9ec/src/main/java/org/kohsuke/github/GHIssue.java#L217-L218

So, this should be an easy fix.

**Comment by gsmet** [comment]
I'll try to have a look after I fixed the other issue.
