### ISSUE TITLE
[QUESTION] How can I use Search API?

### ISSUE THREAD

**Issue by romankh3** [hub4j/github-api#1057]
Hello @hub4j team.
I have a question about client usage.

Currently, I want to search files by name in the whole GitHub and get the file data.

For it I found, that I can use the next endpoints:

For getting an answer about files, use:
`https://api.github.com/search/code?q=FILE_NAME&access_token=ACCESS_TOKEN`

For getting data from the files:
`https://raw.githubusercontent.com/REPO/BRANCH/FILE_PATH`

Can I use your client for this purpose? 
If yes, how can I do it?

Thanks in advance,
Roman.

**Comment by bitwiseman** [comment]
Create a `GitHub` instance and supply your access token. 
Call `gitHub.searchContent()` and use the returned builder to run your query. 
From the result you should be able to get file content.

https://github.com/hub4j/github-api/blob/1f7f646bec0692084e35bfdb81228e83ca2f0765/src/main/java/org/kohsuke/github/GitHub.java#L1241-L1243

**Comment by romankh3** [comment]
thank you
