### ISSUE TITLE
Impossible to get IDs of labels assigned to a `GHIssue`

### ISSUE THREAD

**Issue by dmitrykuzmin** [hub4j/github-api#1059]
When doing issue search, the results are provided as `GHIssue` which, via `getLabels()`, can provide own label list. 

The problem with this is, the `getLabels()` method returns `List<GHLabel>`, and `GHLabel` doesn't store the unique numerical ID assigned to the label by GitHub. This makes API usage problematic for apps that want to utilize the label ID and cannot rely on its mutable parts like name or URL.

**Comment by gsmet** [comment]
I created https://github.com/hub4j/github-api/pull/1062 to fix this issue.
