### ISSUE TITLE
Hi Team,   Is it possible to attach a file while creating a comment for an issue and also mention user names in that for comment references via API?  If it's possible kindly share further details or else kindly share the reason.

### ISSUE THREAD

**Issue by kahilan5** [hub4j/github-api#1090]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**

**Additional context**

**Comment by bitwiseman** [comment]
duplicate of https://github.com/hub4j/github-api/issues/452
