### ISSUE TITLE
Streamline GHEvent parsing from GHEventInfo.type 

### ISSUE THREAD

**Issue by bitwiseman** [hub4j/github-api#1099]
GHEventInfo.type uses Pascal-case names with "Event" on the end instead of snake-case names used elsewhere in the API.  `getType()` does a bunch of processing every time it parses `type` into a `GHEvent`.  We should clean this up.
https://github.com/hub4j/github-api/pull/1096/files#r613635046

**Comment by akashRindhe** [comment]
I'd like to take a crack at this but I'd like to discuss the possible approaches to fix this.

Would a static `Map` from the GitHub defined event type in `Pascal` case to the github-api defined `GHEvent` enum which will be used during the `getType()` call be an acceptable approach?

**Comment by bitwiseman** [comment]
That sounds fine to me.
