### ISSUE TITLE
NullPointerException calling GHCheckRun.update() then .create()

### ISSUE THREAD

**Issue by rdlaitila** [hub4j/github-api#1102]
**Describe the bug**

using org.kohsuke:github-api:1.127 to match version available in recent Jenkins release

Calling GHCheckRun.update() and subsequently GHCheckRunBuilder.create() where GHCheckRun was obtained through GHRepository.getCheckRuns() causes a NullPointerException. 

GHRepository GHObject is null and not being set in this scenario

```
java.lang.NullPointerException
	at org.kohsuke.github.GHCheckRunBuilder.<init>(GHCheckRunBuilder.java:75)
	at org.kohsuke.github.GHCheckRun.update(GHCheckRun.java:339)
	at org.kohsuke.github.GHCheckRun$update.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
```

Official tests show this working only if you call .update() and .create() ONLY IF you have the original reference to the created GHCheckRun https://github.com/hub4j/github-api/pull/980/commits/bde6ad9a06cc71db3d0b8b187bfab5f889175b5c

**To Reproduce**
(roughly)

```groovy
def repository = gh.getRepository(repo)
def checkRun = repository.getCheckRuns(sha).first()
def checkBuilder = checkRun.update()
.... update something ....
def checkUpdated = checkBuilder.create()
```

**Expected behavior**

I should be able to update a GHCheckRun that was queried through the GHRepository

**Workaround**

Manually setup a GHCheckRunBuilder passing in the GHRepository object

```groovy
def repository = gh.getRepository(repo)
def checkRun = repository.getCheckRuns(sha).first()
def checkBuilder = new GHCheckRunBuilder(repository, checkRun.id)
.... update something ....
def checkUpdated = checkBuilder.create()
```

**Comment by bitwiseman** [comment]
Fixed by https://github.com/hub4j/github-api/commit/bf082f2a4650641ec545b7dadaecffba3b58806a 
Releasing in 1.128.
