### ISSUE TITLE
Add ISSUE_COMMENT event type 

### ISSUE THREAD

**Issue by kahilan5** [hub4j/github-api#1104]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**

**Additional context**

**Comment by bitwiseman** [comment]
This is not an issue. 

Please take this kind of question to https://docs.github.com, or https://github.com/hub4j/github-api/discussions , or https://gitter.im/hub4j/github-api

**Comment by bitwiseman** [comment]
There is a an event for issue comments: https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#issue_comment  

It looks like the event is not implemented in this library yet.  Here's a couple of examples off adding an event:  #622, #1087 .

**Comment by gsmet** [comment]
@bitwiseman are you sure it's missing? Because we have `ISSUE_COMMENT` in `GHEvent` and we also have `GHEventPayload.IssueComment`.

**Comment by bitwiseman** [comment]
How did I not see that? 😭
