### ISSUE TITLE
Undeprecate promoted preview API calls

### ISSUE THREAD

**Issue by gadams00** [hub4j/github-api#1143]
https://developer.github.com/changes/2020-08-20-graduate-machine-man-and-sailor-v-previews/
https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/internal/Previews.java#L90 Previews.MACHINE_MAN deprecations (and preview annotations) should no longer be necessary.

**Comment by bitwiseman** [comment]
@gadams00  We should definitely remove `@Deprecated`.  We plan to do that everywhere, see #1003 . 
However, we don't want to remove the Preview yet, because we still need to support older versions of GitHub Enterprise where the endpoint is still in preview.

**Comment by bitwiseman** [comment]
See https://github.blog/changelog/2021-10-14-rest-api-preview-promotions/

All but two previews have graduated.
