### ISSUE TITLE
Set both "page" and "page_size" Params to PagedSearchIterable

### ISSUE THREAD

**Issue by ashok2ashok** [hub4j/github-api#1144]
**Describe the bug**
While trying to limit filename search results to a specific number - say 1, the library ends up iterating over all the pages until every result is collated. I was trying to limit my search result to only one page with a certain page_size. Not looking for the library to parse all possible pages.

**To Reproduce**
1. Perform a Search with a single filename, language and with a page size of 1. Sample given below:
`PagedSearchIterable<GHContent> searchResultsIter = github.searchContent().filename(fileName).language(language).list().withPageSize(1);`

I followed the fix to this: https://github.com/hub4j/github-api/issues/221 to come up with above code. There is no way to specify page param though.

2. Put a debug point on the below line (146 in v1.128) in GitHubPageIterator.java in fetch() method
`assert nextResponse.body() != null;`
3. Verify the `url` param in the method at line 142
`URL url = nextRequest.url();`
4. Resume Program to capture the looped page sizes. On every subsequent loop, the page is incremented automatically.

**Expected behavior**
To get the behavior of below GET URL through a way to specify `page` query param as well:
`https://api.github.com/search/code?q=filename:ThreadSafeLazyLoadedIvoryTowerTest language:Java&per_page=1&page=1`

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.2.3, Mac mini (M1, 2020)
 - Browser: Safari
 - Version: 1.128

**Additional context**
I didn't find a way to limit my search results using both `page_size` and `page` query params. I tried to cheat by using the `q` param but Github doesn't not accept the page params in the query-field.
The first search API call doesn't not include `page` param.
![Screenshot 2021-05-21 at 3 04 38 PM](https://user-images.githubusercontent.com/646649/119117794-3932b180-ba47-11eb-89e0-047bad40d05d.png)

The second auto-search API call added `page` param and increments it everytime until all results are fetched.
![Screenshot 2021-05-21 at 3 05 00 PM](https://user-images.githubusercontent.com/646649/119117871-4d76ae80-ba47-11eb-95ef-6ab9e4bd3b24.png)

**Comment by ashok2ashok** [comment]
I now understand how foolish my question was. I didn't notice the `Iterator`.

Fair warning to folks who are in the same boat - the issue will be masked and you'll be waiting forever if you use similar code to mine as shown below to read the results. `searchResultsIter.forEach` will continue calling the GH-API until the entire results are fetched instead of just the requested page_size. 
```
           PagedSearchIterable<GHContent> searchResultsIter = github.searchContent().filename(fileName).language(language).list().withPageSize(1);
            List<GHContent> searchResultsList = new ArrayList<>();
            searchResultsIter.forEach(searchResultsList::add)
```

Since each call will exactly fetch the requested page_size, the iterator can be used to fetch the exact number of results you need - hopefully a multiple of page_size. To request records individually - use `GHContent ghContent = ghContentPagedIterator.next()` and to request entire page with the requested page_size use `List<GHContent> ghContentList = ghContentPagedIterator.nextPage();`
```
           PagedSearchIterable<GHContent> searchResultsIter = github.searchContent().filename(fileName).language(language).list().withPageSize(1);
            PagedIterator<GHContent> ghContentPagedIterator = searchResultsIter.iterator();
            if(ghContentPagedIterator.hasNext()){
                List<GHContent> ghContentList = ghContentPagedIterator.nextPage();
                //... Do you thing....
            }
```

@kohsuke - Please close this issue as invalid or probably add this to the documentation :)

**Comment by kohsuke** [comment]
`Iterable.forEach()` naturally walks over the entire iterable and my feeling is that nobody should expect otherwise.

Thanks for a very thorough bug report, though.
