### ISSUE TITLE
Create a Pull Request or commit

### ISSUE THREAD

**Issue by AteroConfigs** [hub4j/github-api#1145]
I don´t know if this is the right place to ask, put if don´t quite understand how to create a pull request or a commit.
I would like to know how to make a pull request or commit, with a String of content as comment. Is that possible or am i not quite understanding the possibility's of this API?
  Thanks in advance

**Comment by bitwiseman** [comment]
Please ask in https://github.com/hub4j/github-api/discussions or in https://gitter.im/hub4j/github-api .
