### ISSUE TITLE
Problematic regression with ~/.github file authentication

### ISSUE THREAD

**Issue by gsmet** [hub4j/github-api#1155]
Authenticating with `~/.github` when using `GitHub.connect()` doesn't work anymore in recent versions of the GitHub API.

The client "authenticates" as anonymous instead of using the credentials.

The issue is that the `GitHubBuilder.authorizationProvider` field is never null as it's now initialized to an `ANONYMOUS` instance here: https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/GitHubBuilder.java#L35 .

Thus when arriving here https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/GitHubBuilder.java#L63 , the field is never null and we never get the chance to use the  `~/.github` property file to authenticate a few lines below.

I'm not exactly sure how we want to fix this. A comment in `GitHubBuilder.fromCredentials()` says `@throws IOException If there are no credentials defined in the ~/.github properties file or the process environment.` which is obviously not true anymore.

So:
- we definitely need to test that `authorizationProvider` is not `ANONYMOUS` here: https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/GitHubBuilder.java#L35 .
- I'm not sure if we want to fix the comment and allow anonymous access (but given we explicitly called `fromCredentials()`, I would rather throw an exception) or throw an exception again if we don't have any credentials. The latter would obviously prevent anonymous access.

Note that it can be a bit hard to debug as in my case the GH API was just throwing 404 Not Found errors when trying to do some write operations instead of complaining about the missing credentials.

Also, no idea on how to test this :).

Thoughts?

**Comment by gsmet** [comment]
Workaround is to directly use `GitHubBuilder.fromPropertyFile().build()`.

**Comment by bitwiseman** [comment]
@gsmet  

#945 is definitely the cause of the problem. 

We need to have a mode for testing where the property file location is settable. 

https://github.com/hub4j/github-api/blob/d0912009dd84c55190f01034a59aa3f8ec62fdf5/src/main/java/org/kohsuke/github/GitHubBuilder.java#L180-L183

The code at https://github.com/hub4j/github-api/blob/d0912009dd84c55190f01034a59aa3f8ec62fdf5/src/main/java/org/kohsuke/github/GitHubBuilder.java#L61-L74 should read: 

```
        if (builder.authorizationProvider != AuthorizationProvider.ANONYMOUS)
            return builder;

        try {
            builder = fromPropertyFile();

            if (builder.authorizationProvider != AuthorizationProvider.ANONYMOUS)
                return builder;
```

**Comment by gsmet** [comment]
Yeah, that's the fix I had in mind. The funny part will be to create a test :).

**Comment by bitwiseman** [comment]
@gsmet  Take a look now.
