### ISSUE TITLE
updateCheckRun call fails since 1.128

### ISSUE THREAD

**Issue by hcoles** [hub4j/github-api#1157]
As originally raised in #1156, calls to update check runs that worked in 1.122 now fail once the enum mapping issue is worked around.

The following code

```
   GitHub github = new GitHubBuilder()
       .withOAuthToken("value supplied by github actions")
       .withEndpoint("value supplied by github actions")
       .build();

   GHCheckRun checkRun = repo.createCheckRun("whatever", "value supplied by github actions").withStatus(GHCheckRun.Status.IN_PROGRESS).create();

   repo.updateCheckRun(checkRun.getId())
      .add(output)
      .withConclusion(GHCheckRun.Conclusion.SUCCESS)
      .withStatus(GHCheckRun.Status.COMPLETED)
      .create();
``` 

Runs without issue in 1.122 to 1.127, but fails during the updateCheckRun call from 1.128 onwards with

```
Caused by: org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/XXX/XXX/check-runs/2676567691 {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
    at org.kohsuke.github.GitHubClient.interpretApiError (GitHubClient.java:482)
    at org.kohsuke.github.GitHubClient.sendRequest (GitHubClient.java:409)
    at org.kohsuke.github.GitHubClient.sendRequest (GitHubClient.java:357)
    at org.kohsuke.github.Requester.fetch (Requester.java:76)
    at org.kohsuke.github.GHCheckRunBuilder.create (GHCheckRunBuilder.java:153)
```

@gsmet has indicated that this represents an authentication failure, however it seems strange that the call to create the checkrun succeeds, while the call to update it fails using the same credentials.

**Comment by gsmet** [comment]
Ah yeah, if the check creation succeeds, then there might be something else going on.

**Comment by hcoles** [comment]
Just had a little dig through the git history, and the change that seems to break things is this

https://github.com/hub4j/github-api/commit/8e20f4d9f5ec8e90a6ce673d47b0049cc4ba26fa

**Comment by gsmet** [comment]
Interesting. That explains why I didn't see it in my GitHub App as I'm using the OkHttp connector.

**Comment by hcoles** [comment]
Yes, looks like I can workaround this with OkHttp.

**Comment by bitwiseman** [comment]
@hcoles 
> It seems that github does not support X-HTTP-Method-Override for this call.

😭🤦 

Hm, so if I rerecorded the tests from #754 they would probably now fail.  The question is do we revert #754?

**Comment by hcoles** [comment]
Not directly relevant to this issue, but previously I tried calls out from Junit using a personal access token. This now fails when calling the checks api with a message saying I must authenticate as a github app.

Can anyone confirm that this is a behaviour change, or is my memory flakey? Also, is there an easy workaround?

**Comment by gsmet** [comment]
I think we need to make the correct client the automatic default. It can be done using a MR jar (but it's some infrastructure).

As for your issue with a PAT, you are providing it directly or using `~/.github`? If you provide it to the API, maybe GH has changed something on their side. I must admit that I develop GitHub Apps so I don't really know.

**Comment by gsmet** [comment]
BTW, if you end up having to develop a GitHub App, my pet project might be of interest to you: https://github.com/quarkiverse/quarkus-github-app .

**Comment by bitwiseman** [comment]
@hcoles 
Okhttp also support caching which is generally huge improvement for rate limit usage.
