### ISSUE TITLE
Issue rename event do not contains issue old name

### ISSUE THREAD

**Issue by t0m4uk1991** [hub4j/github-api#1177]
Steps to reproduce:

1. Create an issue:
```
GHRepository repo = getRepository();
GHIssueBuilder builder = repo.createIssue("Some invalid issue name");
GHIssue issue = builder.create();
```
2. Rename an issue
```
issue.setTitle("Fixed issue name");
```

3. Check event and verify we do not have rename object with from/to fields:
```
List<GHIssueEvent> list = issue.listEvents().toList();
assertThat(list.size(), equalTo(1));

GHIssueEvent event = list.get(0);
assertThat(event.getIssue().getNumber(), equalTo(issue.getNumber()));
```

According to the [docs](https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#renamed) renamed even contain rename object with from/to properties for previous/new names. Mappings for this fields were added in scope of [this](https://github.com/hub4j/github-api/pull/1175) PR.

**Comment by bitwiseman** [comment]
@t0m4uk1991 So, this is fixed now right?
