### ISSUE TITLE
Get non-PullRequest issues

### ISSUE THREAD

**Issue by the-redback** [hub4j/github-api#1186]
Hi,

Thanks for this awesome tool. I am quite enjoying working on it.

Just wanted to know, is there any way to get only issues without getting pull requests? When I am requesting getIssue(), I am getting all the pull requests inside the response which can lead to rate limiting.

Thanks

**Comment by bitwiseman** [comment]
Could you give an example of the code you are running?

**Comment by the-redback** [comment]
I am using the following line to get the list. 

```bash
List<GHIssue> allIssues = github.getRepository(org_name + "/" + repo_name).getIssues(GHIssueState.ALL);
```

**Comment by bitwiseman** [comment]
See #1025.  This is a missing feature.
