### ISSUE TITLE
Search API not supporting "page" parameter.

### ISSUE THREAD

**Issue by YasharHND** [hub4j/github-api#1197]
Hi, thanks for providing the GitHub API client; it has been a great help for us.

But there's an issue we have with the `searchIssues()`:
How can we query the search API by passing the `page` and `per_page` making sure that the client only fetches those addressed items?

For example, we need something like this:
```
client.searchIssues()
    .sort(GHIssueSearchBuilder.Sort.UPDATED)
    .order(GHDirection.DESC)
    .q("type:pr is:open")
    .list()
    .atPage(2)
    .withPageSize(10);
```
- Please note that **atPage** is not supported at the moment.
- Also, we don't want the client to fetch all of the items from GitHub but just the ones we've requested for.
- This would be the resulting URL of our request:
`https://api.github.com/search/issues?q=type:pr%20is:open&sort=updated&order=desc&page=2&per_page=10`

I saw some discussion regarding `PagedIterable` #348 but I'm not sure if that resolves our issue.

Thanks in advance.

**Comment by bitwiseman** [comment]
Yes, we do not currently support starting at a specific page.  To iterate over items, you can use the `iterator()`, which will handle fetching pages as needed.  You can also iterate over pages using the iterator's `nextPage()` method:  

https://github.com/hub4j/github-api/blob/7a4af15329a71f44a46f7b4277f162ebcc1020dd/src/main/java/org/kohsuke/github/PagedIterator.java#L120

```
while (iterator.hasNext()) {
     List<GHIssue> page = iterator.nextPage();
     ...
}
```

Are you wanting to only see the items on page 2?   
It would also be reasonable to have a `pageRange(start, end)` method.   
I think what you're asking for should be part of #348, do you agree?

**Comment by YasharHND** [comment]
Yes, for performance reasons, we only want to see items on a specific page without having to fetch items from previous pages.
It can be part of #348.

**Comment by bitwiseman** [comment]
I'll close this in favor of #348.  @YasharHND would you be interested in implementing this?

**Comment by YasharHND** [comment]
Normally I'd love to, but I'm in a time-consuming relocation process and have a very tight schedule.
