### ISSUE TITLE
List workflow runs

### ISSUE THREAD

**Issue by Typraeurion** [hub4j/github-api#1244]
**Feature request**
The GHWorkflow object ought to support listing runs for a workflow, with optional filters.  As the library is currently implemented, I’m having to list all runs for the whole repository and filter runs by workflow which is painfully slow when all I need is the most recent run for a specific workflow.

**Current Implementation**
This is how I have to implement my code currently:

    public GHWorkflowRun getLastWorkflowRun(String authToken,
            String repository, long workflowId, String branch)
                    throws IOException {

        GHRepository repo = getConnection(authToken).getRepository(
                String.format("%s/%s", organization, repository));

        PagedIterable<GHWorkflowRun> workflowRuns =
                repo.queryWorkflowRuns().branch(branch).list();

        PagedIterator<GHWorkflowRun> iter = workflowRuns.withPageSize(1).iterator();
        while (iter.hasNext()) {

            GHWorkflowRun run = iter.next();
            if (run.getWorkflowId() != workflowId)
                continue;

            return run;

        }

        return null;

    }

This could iterate through several (> 100) runs if the workflow hasn’t been run in a while.

**Desired Implementation**
This is how I’d like to implement the code:

    public WorkflowRun getLastWorkflowRun(String authToken,
            String repository, long workflowId, String branch)
                    throws IOException {

        GHRepository repo = getConnection(authToken).getRepository(
                String.format("%s/%s", organization, repository));
        GHWorkflow wf = repo.getWorkflow(workflowId);

        PagedIterable<GHWorkflowRun> workflowRuns =
                wf.queryWorkflowRuns().branch(branch).list();

        PagedIterator<GHWorkflowRun> iter = workflowRuns.withPageSize(1).iterator();
        if (iter.hasNext()) {

            GHWorkflowRun run = iter.next();
            return run;

        }

        return null;

    }

**Platform:**
 - Java 8 (Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode))
 - Spring Boot 2.5.3 (Spring Framework 5.3.8)

**Additional context**
Listing runs for a workflow is supported by the GitHub REST API at endpoint GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs:
https://docs.github.com/en/rest/reference/actions#list-workflow-runs

**Comment by bitwiseman** [comment]
Does https://github.com/hub4j/github-api/pull/1240 address your needs?

**Comment by Typraeurion** [comment]
> Does #1240 address your needs?

Oh, yes!  Strange that issue didn’t show up when I searched for this title.  Thank you.

**Comment by Typraeurion** [comment]
I see that GHWorkflow.listRuns was added in version 1.135.  However, this doesn’t seem to support query parameters like GHRepository.queryWorkflowRuns does.  Are there plans to support something like GHWorkflow.queryRuns?

**Comment by bitwiseman** [comment]
@Typraeurion 
File an issue.  PRs welcome.
