### ISSUE TITLE
Provide create dispatch event api on GHRepository.

### ISSUE THREAD

**Issue by mxandeco** [hub4j/github-api#1246]
Feature request

The `GHRepository` is not exposing a the create dispatch event api the moment.

https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event

I have the changes ready to submit a pr, but I can't find the way to ask for access on the test organization to record the wiremock files, I have generated with my own account, but I need access to generate the proper test files and submit the pull rquest.

**Comment by bitwiseman** [comment]
Sent an invitation.  Please submit the PR.

**Comment by mxandeco** [comment]
> Sent an invitation. Please submit the PR.

changes submitted on https://github.com/hub4j/github-api/pull/1248

**Comment by mxandeco** [comment]
@bitwiseman is there an estimation for a release with those changes? waiting on that for some feature we are building.
thanks very much.

**Comment by bitwiseman** [comment]
Within the week.
