### ISSUE TITLE
`GHDeploymentState` still contains reference to @deprecated javadoc after annotation cleanup

### ISSUE THREAD

**Issue by jfbibeau** [hub4j/github-api#1269]
**Describe the bug**
PR #1184 cleaned up the `@Deprecated` annotations for Preview APIs which is great! However, for `GHDeploymentState`, the `@deprecated` javadoc wasn't removed, see here:

https://github.com/hub4j/github-api/pull/1184/files#diff-e41ba41aaa25735d01eb4efdd7ce10f1cf5c9bfc986a503579a94386ca3744a6R17

**To Reproduce**
1. Use the latest version of this library and have some code like:
```
var deployment = repo.getDeployment(deploymentId);
deployment.createStatus(state)
    .logUrl(logUrl)
    .create();
```
Notice that `logUrl` is still marked as deprecated by IntelliJ because of `* @deprecated until preview feature has graduated to stable`

**Expected behavior**
The javadoc should have been removed at the same time as the annotation so the method isn't marked as deprecated.

Library version: `1.135`

**Comment by ReyhanPatria** [comment]
Hi! I assume the preview feature is stable now, so it's simply removing the deprecated annotation, I'd like to work on this as it would be a simple enough task for my first issue. Thanks!

**Comment by jfbibeau** [comment]
To be clear, the `@Deprecated` annotation is already removed, since the goal of #1184 was to remove them as they were a confusing way to refer to Preview features. However the javadoc remains and needs to be removed. This would be a great first issue!

**Comment by ReyhanPatria** [comment]
Yes, so I'll removing the `@deprecated` from the javadoc, correct?

**Comment by jfbibeau** [comment]
Yup!

**Comment by ReyhanPatria** [comment]
Okay, I'll work on this ASAP.

**Comment by ReyhanPatria** [comment]
I'm having trouble cloning the repo, git is showing errors with the filename being too long and unable to create it. Can you help me with that?
