### ISSUE TITLE
Cannot create new Gist File

### ISSUE THREAD

**Issue by EasyG0ing1** [hub4j/github-api#1278]
So far, I've been able to do the following:

Authenticate with a user token. 

```
GitHub gitHub = GitHub.connectUsingOAuth(token);
boolean authenticated = gitHub.isCredentialValid();
```
Once authenticated I've been able to...

Pull list of users gists:
```
gitHub.getMyself().listGists()
```

Create NEW Gists with a file included:
```
gitHub.createGist()
     .file(filename,contents)
     .description(description)
     .public_(isPublic)
     .create();
```

Delete Gists:
```
gitHub.getGist(gistId).delete();
```

Get a list of files within a given gist:
```
GHGist gist = gitHub.getGist(gistId);
List<String> fileNameList = new ArrayList<>();
for (String filename : gist.getFiles().keySet()) {
     fileNameList.add(filename);
}
```

Though I cannot get the contents of a file this way, I have to pull the files' URL and then get the contents of the file like this:
```
String fileContents = "";
GHGistFile file = gitHub.getGist(gistId).getFile(fileName);
try {
     HttpURLConnection conn = gitHub.getConnector().connect(new URL(file.getRawUrl()));
     conn.setRequestMethod("GET");
     InputStream is = conn.getInputStream();
     fileContents = IOUtils.toString(is, StandardCharsets.UTF_8);
     is.close();
     }
catch (IOException e) {e.printStackTrace();}
return fileContents;
```

THOSE are the things I CAN do ... what I CAN'T seem to do with the API is anything at the gist file level where I need to delete a file, add a file, or update the contents of a file. For example, this code **DOES NOT GENERATE ANY ERRORS**, yet it simply does not work, meaning that the file is never created inside the gist:

```
public static void addFileToGist(String filename, String contents, String gistId) {
     GHGist gist = getGist(gistId);
     try{
          gist.update().addFile(filename,contents);
          CustomAlert.showInfo("File Added");
     }
     catch (IOException e) {e.printStackTrace();}
}
```

Am I doing something wrong? Or is there a way to do what I need to do but I just can't seem to figure it out? Such as - do I need to create new gist files and update them etc. via the HTTPConnector?  If so, can someone who me an example of how to do that?

Mike

**Comment by bitwiseman** [comment]
Adding a file, there is a test example here: 
https://github.com/hub4j/github-api/blob/8be38fcdad8d02636c6067578ee511aaf6adb205/src/test/java/org/kohsuke/github/GHGistTest.java#L44

I can see that the `updated().someactions().update()` syntax is confusing, but it should work.

**Comment by bitwiseman** [comment]
> Though I cannot get the contents of a file this way, I have to pull the files' URL and then get the contents of the file like this:
> 
> ```
> String fileContents = "";
> GHGistFile file = gitHub.getGist(gistId).getFile(fileName);
> try {
>      HttpURLConnection conn = gitHub.getConnector().connect(new URL(file.getRawUrl()));
>      conn.setRequestMethod("GET");
>      InputStream is = conn.getInputStream();
>      fileContents = IOUtils.toString(is, StandardCharsets.UTF_8);
>      is.close();
>      }
> catch (IOException e) {e.printStackTrace();}
> return fileContents;
> ```

It is strange that you cannot get the file contents using `gist.getFiles()` or even `gist.getFile(name)`.  Does this test look like what you are doing? If not, how does it differ? 

https://github.com/hub4j/github-api/blob/8be38fcdad8d02636c6067578ee511aaf6adb205/src/test/java/org/kohsuke/github/GHGistTest.java#L130-L143

**Comment by EasyG0ing1** [comment]
@bitwiseman 

Thank you for responding.

On your last question ... take this code for example:

```
for (GHGist gist : gitHub.getMyself().listGists()) {
    System.out.println(gist.getGistId());
    System.out.println("---------------------------------------------");
    for (String filename : gist.getFiles().keySet()) {
        GHGistFile file = gist.getFiles().get(filename);
        System.out.println("Name: "+file.getFileName());
        System.out.println("URL: "+file.getRawUrl());
        System.out.println("Size: "+file.getSize());
        System.out.println("Lang: "+file.getLanguage());
        System.out.println("Type: "+file.getType());
        System.out.println("Content: "+file.getContent());
        System.out.println("---------------------------");
    }
}
```

Here is the output from just one of the loops:

```
62e15df9eb6e79570cc44f9db8c9748f
---------------------------------------------
Name: Router.txt
URL: https://gist.githubusercontent.com/EasyG0ing1/62e15df9eb6e79570cc44f9db8c9748f/raw/cbcf783a0f4e8bba1db8a2d65e46add8bf2f06fa/Router.txt
Size: 13192
Lang: Text
Type: text/plain
Content: null
---------------------------
Name: SwitchA.text
URL: https://gist.githubusercontent.com/EasyG0ing1/62e15df9eb6e79570cc44f9db8c9748f/raw/6cf45d08bb95344aac0311a69e1e473eceff90cd/SwitchA.text
Size: 3212
Lang: null
Type: text/plain
Content: null
---------------------------
Name: SwitchB
URL: https://gist.githubusercontent.com/EasyG0ing1/62e15df9eb6e79570cc44f9db8c9748f/raw/c2089f9f1aad87ce95de85ebbecec4f434c329be/SwitchB
Size: 3390
Lang: null
Type: text/plain
Content: null
---------------------------
Name: SwitchC.txt
URL: https://gist.githubusercontent.com/EasyG0ing1/62e15df9eb6e79570cc44f9db8c9748f/raw/55a26541a5c9af59ae78b35ac6e64ff982f9e653/SwitchC.txt
Size: 2902
Lang: Text
Type: text/plain
Content: null
---------------------------
```

Notice the content is always null ...

**Comment by EasyG0ing1** [comment]
@bitwiseman 

When I ran this code:

```
gitHub.getGist(gistId).update().description(description).addFile(filename,contents).update();
```

I got this error and IntelliJ sent the cursor to the .update() statement at the end of the sentence:

```
org.kohsuke.github.GHIOException: Failed to set the custom verb
```

**Comment by EasyG0ing1** [comment]
@bitwiseman 

OK, so this is interesting ... when I created a new gist with an included new test file with the library, I am able to access the file contents just using file.getContent() ... but the gists that I have had in there for a long time cannot be retrieved using the same method.

I'm thinking there's a reason for that ...???

**Comment by bitwiseman** [comment]
`org.kohsuke.github.GHIOException: Failed to set the custom verb` - Java 16+ issue: #1202

**Comment by EasyG0ing1** [comment]
@bitwiseman 

Implementing the OKHttp connector into the instantiation of the GitHub class fixed my ability to get to those files, and I'm going to assume that it will fix everything else. I'll change the code in those places and let you know ...

One thing about building the object using GitHubBuilder is that I can't seem to get myself out of the final object ...

This code:
```
GitHub gitHub = GitHubBuilder.fromEnvironment().withConnector(new OkHttpConnector(new OkHttpClient())).build();
GHMyself mySelf = gitHub.getMyself();
```
Throws this error in the second line:
```
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: This operation requires a credential but none is given to the GitHub constructor
```
But it has nothing to do with the OKHttp connector as I experienced that error before from using the GitHubBuilder class to create the GitHub object ... not sure why but the credentials don't seem to get passed into gitHub in a way that allows me to get access to myself, which is really only needed to get the List of gists in the account.

It even throws the error when I do this, which lets me know that the authentication is there ... it's just not there for myself
```
gitHub = GitHubBuilder.fromEnvironment().withConnector(new OkHttpConnector(new OkHttpClient())).build();
if (gitHub.isCredentialValid()) {
    GHMyself mySelf = gitHub.getMyself();
}
```

**Comment by EasyG0ing1** [comment]
@bitwiseman 

That did the trick ... this was all it took to fix everything:
```
gitHub = new GitHubBuilder().withOAuthToken(token).withConnector(new OkHttpConnector(new OkHttpClient())).build();
```

Thank you ... not sure if you have this pull or not, but it might be a good idea to explicitly state [on this page](https://github-api.kohsuke.org/) that the OKHttp connector should always be used in the build statement.

I realize there is a comment about OKHttp at the bottom of the page, but there was certainly no indication there that I would have problems without using it ... it reads like using OKHttp is an option ... and that it won't tax your account ... but nothing at all about it being necessary for functionality.

**Comment by bitwiseman** [comment]
Okhttp is just an option. It is not required. 
Perhaps the error thrown when using Java 17 should be more verbose about options for mitigating the problem.

**Comment by EasyG0ing1** [comment]
@bitwiseman - You certainly won't get any arguments from me on that statement!

**Comment by EasyG0ing1** [comment]
I would like to add, that even when using the OKHttp connector to create a GitHub object, when I get a list of all Gists using this method:
```
gitHub.getMyself().listGists();
```
Then interrogate that list and get the contents of each file within the each Gist, the contents come back null. I have to first get a list of all the GistId's like this:
```
 List<String> gistIDs = new ArrayList<>();
 for (GHGist gist : gitHub.getMyself().listGists()) {
     String gistID = gist.getGistId();
     gistIDs.add(gistID);
 }
```
Then iterate through the list of IDs and get each Gist like this:
```
for (String gistID : gistIDs) {
    GHGist gist = gitHub.getGist(gistID);
    for (String filename : gist.getFiles().keySet()) {
        GHGistFile file = gist.getFiles().get(filename);
        System.out.println("Contents: " + file.getContent());
    }
}
```
Doing that will give me the contents of each file within each gist.

**Comment by EasyG0ing1** [comment]
@bitwiseman This is flagged as needing more information?

**Comment by bitwiseman** [comment]
@EasyG0ing1 
Need more information - there was a bunch of back and forth. I wasn't sure I caught everything.  Probably a hold over from earlier.

As of v1.300, the default connector for Java 11+ is now `HttpClientGitHubConnector`. That addresses your original issue.

You last comment - https://github.com/hub4j/github-api/issues/1278#issuecomment-959355242 sounds like a different issue but definitely a bug.  Please open a new issue for that.  Thanks!

**Comment by EasyG0ing1** [comment]
@bitwiseman - YES, 1.300 gets me connected with the HttpClientGitHubConnector. 

You guys work fast over there - Thank you!

:-)
