### ISSUE TITLE
Enhancement Request: Change Gist Public State

### ISSUE THREAD

**Issue by EasyG0ing1** [hub4j/github-api#1303]
There seems to be no way of toggling the state of a Gist object between private and public. The only way it can be done is to first copy the Gist object and all of the files within it locally, then delete the Gist entirely then create a new Gist as either public or private, then re-create every file from the local copy.

It would be convenient to be able to make this call to the API and simply toggle the state from public to private etc.:

```GistObject.update().setPublic(boolean).update();```

**Comment by EasyG0ing1** [comment]
As I was working on my code, It occurred to me that changing the public state of a Gist might have unwanted consequences if a public Gist has been forked. I'm not entirely sure how that would manifest if a forked public Gist suddenly had its state changed to private. If it would break those forks, then it obviously makes sense that a public Gist should never have the option of being changed to private, which means that this feature should not be implemented.

**Comment by gsmet** [comment]
This library depends on the availability of the feature in the GitHub REST API.

I have seen no such thing as the ability to change the visibility of Gists here: https://docs.github.com/en/rest/reference/gists but I haven't looked too hard :).

**Comment by bitwiseman** [comment]
Yeah, this is not supported by the GitHub API.  Closing.
