### ISSUE TITLE
[Enhancement] How do I get a reply in a team discussion?

### ISSUE THREAD

**Issue by WorriedArrow** [hub4j/github-api#1347]
##### Thanks

**Comment by bitwiseman** [comment]
How do would you do this using the REST API?

**Comment by WorriedArrow** [comment]
I'm not sure. It doesn't look like they have any documentation on it, though I'm not very familiar with the REST API.

**Comment by gsmet** [comment]
There is an endpoint here: https://docs.github.com/en/rest/reference/teams#discussions .

And I think we already have an embryon of this here for instance: https://github.com/hub4j/github-api/blob/bcb71a3c318d243c92b757310cf153b8afc983d5/src/main/java/org/kohsuke/github/GHTeam.java#L135 . There might be some things missing but it should be easy to add them.

**Comment by WorriedArrow** [comment]
Ah! Thank you very much!

**Comment by WorriedArrow** [comment]
Hmm... this seems like it won't get replies, but rather discussions.

**Comment by gsmet** [comment]
Hmmm. Have a look at the payload you obtain anyway just in case. But it looks like the comments aren't there.

In this case, your best bet will be the GraphQL API: https://docs.github.com/en/graphql/reference/objects#teamdiscussion .

**Comment by WorriedArrow** [comment]
Thanks!
