### ISSUE TITLE
`GHEventPayload.Push.getPusher()` returns `null` from `getEvents()`

### ISSUE THREAD

**Issue by nieanlei** [hub4j/github-api#1374]
@Test
    public void testEventApi() throws Exception {
        final GitHub gitHub2 = GitHub.connectUsingOAuth("token");
        for (GHEventInfo ev : gitHub2.getEvents()) {
            if (ev.getType() == GHEvent.PUSH) {
                if (GHEvent.PUSH == ev.getType()) {
                    GHEventPayload.Push push = ev.getPayload(GHEventPayload.Push.class);
                    //push.getPusher()  this is Null , I Need getPusher
                    System.out.println(push.getPusher().getName());
                    for (GHEventPayload.Push.PushCommit commit : push.getCommits()) {
                        //commit.getCommitter() this is Null, I Need getCommitter
                        System.out.println(commit.getCommitter().getName());
                    }

                }
            }
        }
    }

**Comment by nieanlei** [comment]
https://github.community/t/here-is-a-problem-with-the-api/229353/6  this my question

**Comment by bitwiseman** [comment]
This library does not control what  GitHub returns.  Sounds like a bug in GitHub?

**Comment by bitwiseman** [comment]
Okay, let's clarify something: 
The REST API call to https://api.github.com/repos/nieanlei/github-test/commits is not the same as the the commits returned in the `GHEventPayload.Push` event `getCommits()`.  

Also, I think `getEvents()` does not return the same information that is returned by actually listen for events via webhooks.  

I'm sorry to say, but in order to establish that the problem is in this library, you need to need to establish a server that GitHub can contact.  You might do this via https://smee.io/ . That will let you see the JSON that is actually being sent. 

Another question: what is it you are trying to accomplish? It is possible that what you are trying do is better done using a different part of the API.

**Comment by nieanlei** [comment]
When binding webhooks, I need to pull git history commit info, I need to differentiate between different events like push,merge, and know who did it

**Comment by nieanlei** [comment]
> 好的，让我们澄清一下：对https://api.github.com/repos/nieanlei/github-test/commits 的 REST API 调用与event中返回的提交不同。[](https://api.github.com/repos/nieanlei/github-test/commits)`GHEventPayload.Push``getCommits()`
> 
> 另外，我认为`getEvents()`不会返回与通过 webhook 实际监听事件返回的信息相同的信息。
> 
> （这两个都是 GitHub 服务的事实，这个库无法控制它。）
> 
> 很抱歉，但为了确定问题出在这个库中，您需要建立一个 GitHub 可以联系的服务器。您可以通过https://smee.io/执行此操作。这将使您看到实际发送的 JSON。
> 
> 另一个问题：你想要完成什么？使用 API 的不同部分可能会更好地完成您尝试做的事情。

When binding webhooks, I need to pull git history commit info, I need to differentiate between different events like push,merge, and know who did it

> ，让我们讨论一下：对https://api.github.com/repos/nieanlei/github-test/commits 的REST API调用与event中的提交不同。[](https://api.github.com/repos/nieanlei/github-test/commits)`GHEventPayload.Push``getCommits()`
> 
> 另外，我认为`getEvents()`不会返回与通过 webhook 实际监听事件返回的信息相同的信息。
> 
> （这两个都是 GitHub 服务的事实，这个库无法控制它。）
> 
> 很抱歉，但要确定在这个库中出的，您可以联系一个 GitHub 的服务器。您的[https:](https://smee.io/) // smeeio /执行此操作需要通过创建此问题。您可以查看实际的 JSON。
> 
> 问题：您想要完成什么使用 API 的不同部分可能会更好地完成您尝试另一个做的事情。
you mean : event.getCommits().get(0).getCommitter()  = event.getPusher?

**Comment by bitwiseman** [comment]
Here is an example of a `PushEvent` returned from https://api.github.com/repos/hub4j/github-api/events :
```json
[
...
 {
    "id": "20255014704",
    "type": "PushEvent",
    "actor": {
      "id": 1958953,
      "login": "bitwiseman",
      "display_login": "bitwiseman",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bitwiseman",
      "avatar_url": "https://avatars.githubusercontent.com/u/1958953?"
    },
    "repo": {
      "id": 617210,
      "name": "hub4j/github-api",
      "url": "https://api.github.com/repos/hub4j/github-api"
    },
    "payload": {
      "push_id": 9101603422,
      "size": 5,
      "distinct_size": 5,
      "ref": "refs/heads/main",
      "head": "9b164cad0811a9ff73cb9cd0970901e414ee3609",
      "before": "0e41ccb5f13f32b7395245155db9650edcf8f1d9",
      "commits": [
        {
          "sha": "cfdfca995a411f158d4282f3ee5d845a1055dac7",
          "author": {
            "email": "guillaume.smet@gmail.com",
            "name": "Guillaume Smet"
          },
          "message": "Fix installation payload handling\n\nIn the installation payload, the repository doesn't contain a lot of\ninformation and it especially does not contain the URL.\n\nTests are passing because we use an offline GitHub instance for testing\nthe payloads.",
          "distinct": true,
          "url": "https://api.github.com/repos/hub4j/github-api/commits/cfdfca995a411f158d4282f3ee5d845a1055dac7"
        },
        {
          "sha": "83386fc03be3817526c7d7749a4be4bdd2a0a5f1",
          "author": {
            "email": "guillaume.smet@gmail.com",
            "name": "Guillaume Smet"
          },
          "message": "Add a test for repository population of installation event payloads",
          "distinct": true,
          "url": "https://api.github.com/repos/hub4j/github-api/commits/83386fc03be3817526c7d7749a4be4bdd2a0a5f1"
        },
        {
          "sha": "ea9cfef98122784de835acaa5576380d828ccb93",
          "author": {
            "email": "bitwiseman@gmail.com",
            "name": "Liam Newman"
          },
          "message": "Apply suggestions from code review",
          "distinct": true,
          "url": "https://api.github.com/repos/hub4j/github-api/commits/ea9cfef98122784de835acaa5576380d828ccb93"
        },
        {
          "sha": "c87903ef7b6351e883ee2100270efa9be33b2023",
          "author": {
            "email": "bitwiseman@gmail.com",
            "name": "Liam Newman"
          },
          "message": "Update src/main/java/org/kohsuke/github/GHEventPayload.java",
          "distinct": true,
          "url": "https://api.github.com/repos/hub4j/github-api/commits/c87903ef7b6351e883ee2100270efa9be33b2023"
        },
        {
          "sha": "9b164cad0811a9ff73cb9cd0970901e414ee3609",
          "author": {
            "email": "bitwiseman@gmail.com",
            "name": "Liam Newman"
          },
          "message": "Merge pull request #1371 from gsmet/installation-fix\n\nFix installation payload handling",
          "distinct": true,
          "url": "https://api.github.com/repos/hub4j/github-api/commits/9b164cad0811a9ff73cb9cd0970901e414ee3609"
        }
      ]
    },
    "public": true,
    "created_at": "2022-02-14T22:03:52Z",
    "org": {
      "id": 54909825,
      "login": "hub4j",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/hub4j",
      "avatar_url": "https://avatars.githubusercontent.com/u/54909825?"
    }
  },
...     
]
```

As you can see, it does not include the `pusher` field and the commits do not include the `committer` field.  However, the documentation for the [webhook push event](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push) does include those fields. 

If there is a bug here it is that this library uses the same data objects for events and webhooks when they are in fact significantly different.  

Openning #1375 to address this.
