### ISSUE TITLE
GHOrganization.Permission does not support custom roles

### ISSUE THREAD

**Issue by jgangemi** [hub4j/github-api#1377]
github added the ability to define custom roles, however the `Permission` object is an enum and this not extensible.

i was thinking of converting the `Permission` enum into a class and creating constants for the static roles, however that would be a breaking change. i could probably introduce a new class to work around this but don't have a lot of great names, `RolePerm` perhaps?

thoughts?

**Comment by bitwiseman** [comment]
`RolePermission` seems fine.  Go for it and we can adjust it when it reaches PR if it seems needed.

**Comment by jgangemi** [comment]
resolved by #1403
