### ISSUE TITLE
Determining result of Workflow Dispatch

### ISSUE THREAD

**Issue by BenF99** [hub4j/github-api#1380]
### Unable to identify the cause of failure for workflow dispatch event

![image](https://user-images.githubusercontent.com/55698282/155540552-756db89d-85fd-43b7-8bc4-97d45c157394.png)

As we known, `dispatch` doesn't return anything, making it extremely difficult to identify the cause of failure for a workflow trigger.
As an example, assume a workflow requires a specific input which is not provided in the call - the method has no way of providing us with such information on failure. 

Do we have a way to identify at minimum the status code returned from the dispatch?

**Comment by ketronkowski** [comment]
I have a case where a 403 is being returned from the GitHub "dispatches" API call, it would be very useful for the method caller (of `dispatch(...)`) to know that information through a thrown IOException based on receiving a 400/500 error from the Github API.

**Comment by gsmet** [comment]
PR is here: https://github.com/hub4j/github-api/pull/1455 .

I don't know what I was thinking when I implemented it...

**Comment by ketronkowski** [comment]
Will a new release of the API come out soon with this fix?
