### ISSUE TITLE
Update GHTeam APIs to not use deprecated urls - 15th March effective

### ISSUE THREAD

**Issue by AmyShields-EN0085** [hub4j/github-api#1386]
GHTeam APIs updated to not use deprecated urls - comes into effect 22nd March

Communication from GitHub -

https://github.blog/changelog/2022-02-22-sunset-notice-deprecated-teams-api-endpoints/

In [early 2020](https://developer.github.com/changes/2020-01-21-moving-the-team-api-endpoints/), we moved the Teams API from a top-level path under /teams/:team_id to a scoped path under the organization that owns the team like /organizations/:org_id/team/:team_id and added support to make the API available under a named path like /orgs/:org/teams/:team_slug.

Over the next few weeks, we will be sunsetting the API endpoints under /teams/:team_id.

**Removal
March 15, 2022 at 14:00 UTC**

**Affected endpoints**
GET /teams/:team_id
PATCH /teams/:team_id
DELETE /teams/:team_id
GET /teams/:team_id/teams
GET /teams/:team_id/repos
GET /teams/:team_id/repos/:owner/:repo
PUT /teams/:team_id/repos/:owner/:repo
DELETE /teams/:team_id/repos/:owner/:repo
GET /teams/:team_id/projects
GET /teams/:team_id/projects/:project_id
PUT /teams/:team_id/projects/:project_id
DELETE /teams/:team_id/projects/:project_id

**Steps to take**
The easiest way to update your code is to switch to the /organizations/:org_id/team/:team_id path. If you're unsure of what org_id to use, you can GET the current team under /teams/:team_id and find the id field inside the organization hash in the response.

**Comment by gsmet** [comment]
I'll have a look at this one tonight.

Thanks @AmyShields-EN0085 for opening the issue.

**Comment by AmyShields-EN0085** [comment]
This comes into effect 15th march - not 22nd! Apologies!

**Comment by gsmet** [comment]
Even better :).

**Comment by gsmet** [comment]
@bitwiseman I started working on this one but I don't have the permissions to properly regenerate the required snapshots. Most of the Teams API requires me to be an admin.

**Comment by bitwiseman** [comment]
@gsmet I'll get you those tonight.

**Comment by bitwiseman** [comment]
@gsmet You are already an owner in `hub4j-test-org`. 

I'm a little concerned.  If there are versions of GitHub Enterprise still using these old endpoints, they will stop working with this change.  But that is lower priority bug that we can address if it comes up.

**Comment by gsmet** [comment]
> You are already an owner in hub4j-test-org.

Hmmm. That is weird because it looked a lot like I didn't have all the required permissions. I'll have a closer look tonight.

> I'm a little concerned. If there are versions of GitHub Enterprise still using these old endpoints, they will stop working with this change. But that is lower priority bug that we can address if it comes up.

I think they will have to stay on older versions of the GitHub API.
Other option would be to introduce some sort of dialect which would be dependent on the version but really not sure it's worth it.

**Comment by klosowskiMikolaj** [comment]
Hello @gsmet 
Do you have a working timeline for the fix - will you be able to provide it before the next brownout (March 8, 2022, for 24 hours starting at 14:00 UTC)?

**Comment by gsmet** [comment]
I'm back at it today.

**Comment by gsmet** [comment]
1.303 has been released. Please update before the next brownout of March 8th and report back if you encounter any issue.

**Comment by chadlwilson** [comment]
Updated a plugin i help maintain in https://github.com/gocd-contrib/github-oauth-authorization-plugin/pull/197 - seems to be working fine - thanks @gsmet !
