### ISSUE TITLE
No way to access pull request review comment details

### ISSUE THREAD

**Issue by nahsra** [hub4j/github-api#1420]
I'm not sure of the intended way I should access pull request review comment details.

Specifically, this API here: https://docs.github.com/en/rest/reference/pulls#get-a-review-comment-for-a-pull-request

I can get a list of comments with `GHPullRequest#listReviewComments()`, but they don't contain the commit ID, diff hunk, etc. The comments returned from that API contain a URL to retrieve more details, but after upgrading to the latest version and seeing the stdout warnings I'm not sure how/when I should use the connector (if ever?).

**Comment by bitwiseman** [comment]
@nahsra 
I have hidden the above comment to save anyone from having to look at the code. You're right, only people who hate the world would do that. 

However, you can turn hate into love - submit a PR adding the missing properties to [GHPullRequestReviewComment](https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/GHPullRequestReviewComment.java) .  You don't need the `@JsonProperty` lines, our Jackson config already maps `my_item` into `myItem` automatically.  The only other thing you'd need to do is update the tests to verify the properties contain valid values.  

It is up to you @nahsra .  Bring the love. 

> upgrading to the latest version and seeing the stdout warnings I'm not sure how/when I should use the connector (if ever?)

Stdout warnings? Perhaps this is another bug to be filed?
