### ISSUE TITLE
Oauth2 The authorization request Token timed out seriously

### ISSUE THREAD

**Issue by nieanlei** [hub4j/github-api#1422]
![image](https://user-images.githubusercontent.com/30683887/162450668-1e2c698b-ce63-4c9c-8c15-50773b0df873.png)

![image](https://user-images.githubusercontent.com/30683887/162450427-42e53d40-3497-4421-b822-328186ddf838.png)

**Comment by nieanlei** [comment]
Requests time out very frequently

**Comment by bitwiseman** [comment]
This is due to a network issue in your infrastructure. It is not a bug in this library.

You might try switching to using okhttp for connecting. It tends to do a better job of retrying when this kind of problem occurs.

**Comment by nieanlei123** [comment]
Thinks

**Comment by nieanlei123** [comment]
Thanks

**Comment by nieanlei** [comment]
> 这是由于您的基础架构中的网络问题。这不是这个库中的错误。
> 
> 您可以尝试切换到使用 okhttp 进行连接。当发生此类问题时，它往往会更好地重试。
It's really a network problem   I solved the problem    Modifying the hosts file

199.232.69.194  github.global.ssl.fastly.net
140.82.112.3 github.com
140.82.113.4 github.com
185.199.108.153 assets-cdn.github.com
185.199.109.153 assets-cdn.github.com
185.199.110.153 assets-cdn.github.com
185.199.111.153 assets-cdn.github.com
