### ISSUE TITLE
Missing Workflow Job's running machine type (ubuntu, windows, macos) 

### ISSUE THREAD

**Issue by yusuf-erdem** [hub4j/github-api#1445]
Hello,
I need to find Workflow Job's running machine type (ubuntu, windows, macos). Github Api has labels property which includes that information. It seems like you did not provide **labels** information of GHWorkflowJob. Can you provide that or do you have information about job's running mactine type already? Thank you for your supports...

**Comment by bitwiseman** [comment]
Is this information in the REST API?

**Comment by yusuf-erdem** [comment]
> Is this information in the REST API?

Yes it is already included, https://docs.github.com/en/rest/actions/workflow-jobs#get-a-job-for-a-workflow-run
There is PR for this addition, you can check it...

https://github.com/hub4j/github-api/pull/1447
