### ISSUE TITLE
secret in Repository WebHooks does not exist

### ISSUE THREAD

**Issue by oubaydos** [hub4j/github-api#1470]
Hello, 
the option to set the secret when creating a new webhook is not implemented, i guess it is a must do, because must of webhooks wont work without the secret.
```java
github.getRepository(name).createWebHook(new URL(webHookUrl))
```
has no option to set the secret

**Comment by AlexanderZobkov** [comment]
Hello,
The "createWebHook" method is a kind of simpler version of "createHook" method. 
If you need to set webhook secrets and etc, use "createHook" method specifying config map with keys as specifed in 
https://docs.github.com/en/rest/webhooks/repos#create-a-repository-webhook.

**Comment by oubaydos** [comment]
hey, thank you for the response, could i open a pull request with an implementation of this function 
```java
     public GHHook createWebHook(URL url, String secret) throws IOException;
```
