### ISSUE TITLE
Cannot delete blob from tree

### ISSUE THREAD

**Issue by Cloudate9** [hub4j/github-api#1484]
**Describe the bug**
While there is a way to create a tree (`GHTreeBuilder`) and to add an object to the tree (`GHTreeBuilder#add`), there is no clear way to remove an object (i.e. remove a file upon committing the tree + updating a ref). According to the [GitHub REST api docs](https://docs.github.com/en/rest/git/trees#create-a-tree), one should be able to remove a file by passing in a null sha. This is not possible with `GHTreeBuilder#add`, as it requires a non-null content (not sha). 

Is there something I'm missing here? Is that a separate method for this in the api?
Note: `GHRepository#getContent#delete` will not suffice. That requires me to do a commit for every single file I want to delete, which is not ideal.

**To Reproduce**
1. Create a new `GHTreeBuilder`, with a `baseTree`
2. Try to pass in a null value for content in `GHTreeBuilder#add`
3. Be sad at the compile errors

**Expected behavior**
Upon committing the tree and updating a ref, the file with a null sha passed should be deleted.

**Comment by russellbanks** [comment]
This issue needs bumping because currently as you said I have to do a commit for every file. I've tried passing an empty ByteArray and that just removes all content from the file.

**Comment by bitwiseman** [comment]
@russellbanks 
PRs welcome.  As you can see, I don't have a lot of bandwidth for this project right now.
