### ISSUE TITLE
NPE on PageIterator.next()

### ISSUE THREAD

**Issue by goldbal330** [hub4j/github-api#1503]
**Describe the bug**
NPE sporadically gets thrown by PageIterator (line 74) when PageIterator.hasNext() is invoked.

**To Reproduce**
I was able to reproduce behavior in this simple jUnit Test:

```
PageIterator<String> pagedIterator = new PagedIterator<>(((List<String[]>)  new ArrayList<
String>[]()).iterator();
Assertions.assertFalse(pagedIterator.hasNext());
```

It seems like in this corner case currentPage does not get initialized and NPE gets thrown when calling currentPage.length on line 75.

**Expected behavior**
NPE should not be thrown and hasNext() should return false.

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome, safari]
 - Version [1.306]

**Additional context**
Proposed fix: 

```
  public boolean hasNext() {
        fetch();
        return (currentPage != null && currentPage.length > nextItemIndex);
    }
```

**Comment by bitwiseman** [comment]
PR and test welcome.
