### ISSUE TITLE
Webhook events

### ISSUE THREAD

**Issue by jacoobes** [hub4j/github-api#1505]
Hi, I might be missing something in the library, but I need live data from web-hooks, I can't seem to find documentation or an issue for listening to hooks. Thanks!

**Comment by gsmet** [comment]
This library won't handle the webhook part but most of the useful payloads are implemented here (one nested class per payload type): https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/GHEventPayload.java .

As for reacting to webhooks (and handling all the plumbing), you might be interested in this little library of mine that allows to develop GitHub Apps in Java and react to events: https://github.com/quarkiverse/quarkus-github-app .

It's based on this very library and Quarkus (but very little Quarkus knowledge is required to get something working).

Of course, you can also handle webhooks yourself and just use the Hub4j GitHub API to handle the payload parsing and the subsequent API calls.

**Comment by jacoobes** [comment]
Thanks for the info!

**Comment by jacoobes** [comment]
Hi, a question just popped up in my brain

> This library won't handle the webhook part but most of the useful payloads are implemented here (one nested class per payload type): https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/GHEventPayload.java .
> 
> As for reacting to webhooks (and handling all the plumbing), you might be interested in this little library of mine that allows to develop GitHub Apps in Java and react to events: https://github.com/quarkiverse/quarkus-github-app .
> 
> It's based on this very library and Quarkus (but very little Quarkus knowledge is required to get something working).
> 
> Of course, you can also handle webhooks yourself and just use the Hub4j GitHub API to handle the payload parsing and the subsequent API calls.
Would I be using, if i wanted the github api to handle it, the GithubConnector to handle the payload?

**Comment by gsmet** [comment]
You would have to use this method https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/GitHub.java#L931-L951 to parse the payloads.

**Comment by jacoobes** [comment]
tysm
