### ISSUE TITLE
Javadoc for this library no longer found

### ISSUE THREAD

**Issue by AmyShields-EN0085** [hub4j/github-api#1509]
When looking for documentation on library ie: https://github-api.kohsuke.org/apidocs/index.html

You get a 404 page not found.

Would be really handy to have these docs back up!

**Comment by arslanakhtar61** [comment]
Yes, please. The docs URL is not longer working!

**Comment by arslanakhtar61** [comment]
Where can we find the html file for javadocs in the repo so that we can manually load it locally?

**Comment by bitwiseman** [comment]
Fixed by reverting to 1.302 api doc.
