### ISSUE TITLE
Read timed out while connecting to 

### ISSUE THREAD

**Issue by amigax** [hub4j/github-api#1550]
This was working fine until recently, now when I try to commit I get:
INFO: Read timed out while connecting to https://api.github.com/repos/XXX/ZZZ/git/trees. Sleeping 100 milliseconds before retrying... ; will try 2 more time(s)

Eventually it says 
Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/repos/XXX/ZZZZ/git/trees

what could the issue be?

**Comment by bitwiseman** [comment]
Are you running using Java 8?
