### ISSUE TITLE
Enhancement: get the `allow_forking` flag value for a `GHRepository`

### ISSUE THREAD

**Issue by zemunk** [hub4j/github-api#1588]
I'd like to contribute a small enhancement to the `GHRepository` class and add a method to get the value of the `allow_forking` flag.

From the [GitHub REST API Docs](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28):

>allow_forking boolean
Either true to allow private forks, or false to prevent private forks.
Default: false

**Example context:**
I need to fork repositories in a multistep workflow, but for `private` and `internal` repos forking can be disabled.
In these cases instead of getting an exception when trying to fork, I'd like to be able to check at the very beginning if it is possible at all and provide a proper message to the users.

**Comment by bitwiseman** [comment]
Go for it. PRs welcome.

**Comment by varun-khachane** [comment]
Hi, I would like to work on this. Can you assign it to me?
