### ISSUE TITLE
Files are converted to LF line endings on commit

### ISSUE THREAD

**Issue by russellbanks** [hub4j/github-api#1591]
**Describe the bug**
Data is always commited with LF line endings.

**To Reproduce**
1. Commit a text file to a GitHub repository with CRLF line endings (replace \n with \r\n)
2. It now has LF line endings

This is my code (Kotlin)
```kotlin
repository?.createCommit()
    ?.message(getCommitMessage())
    ?.parent(branch?.getObject()?.sha)
    ?.tree(
        repository
            .createTree()
            .baseTree(repository.getBranch(branch?.ref).shA1)
            .apply {
                files.forEach { (path, content) ->
                    if (content != null) {
                        add(path, content.replace("\n", "\r\n"), false)
                    }
                }
            }
            .create()
            .sha
    )
    ?.create()
    ?.also { branch?.updateTo(it.shA1) }
```

**Expected behavior**
The data should be commited with CRLF line endings.

**Additional context**
I'm not sure whether this is a GitHub API issue, or an issue with this library.

**Comment by bitwiseman** [comment]
This is probably due to underlying git settings. 
https://stackoverflow.com/questions/5834014/lf-will-be-replaced-by-crlf-in-git-what-is-that-and-is-it-important

If not, then it is a behavior of GitHub.  Not something we can fix.
