### ISSUE TITLE
Updating multiple files in one commit

### ISSUE THREAD

**Issue by vrozkovec** [hub4j/github-api#1620]
Hi, 
I have searched for a way how to include more files in one commit and I could not find my way around, is it possible?
I know I can get `GHContent`  for file in the repository and then call `update` method on it, but that creates one commit for each file updated and for certain workflows it would be better to include several such updates in one commit.
Could you, please, direct me to a way how multiple updates can be grouped under one commit, if that's possible?

Thank you!

**Comment by bitwiseman** [comment]
I believe this is done via Git Trees: https://docs.github.com/en/rest/git/trees . You create a tree and then create a commit for that tree. 

https://github.com/hub4j/github-api/blob/main/src/test/java/org/kohsuke/github/GHTreeBuilderTest.java

**Comment by vrozkovec** [comment]
Ah, awesome, thanks a lot!
