### ISSUE TITLE
Feature Request: GitHub autolink

### ISSUE THREAD

**Issue by dgeissl** [hub4j/github-api#1627]
It's very common to have links to external issue trackers and those can be easily integrated with the autolink feature. 
Currently there is no programming interface to access this feature with github-api.

However once one has enough repositories it's tedious to do that by hand. It would be a pleasure to see that feature in the github-api project to automate this task.

**Additional context**
[Repository autolinks API documentation](https://docs.github.com/en/rest/repos/autolinks?apiVersion=2022-11-28)

**Comment by Alaurant** [comment]
@bitwiseman 
I'm interested in contributing a solution for this. Would you please invite me to the `hub4j-test-org` organization? 

However, I noticed that the Autolink feature may not be available for the free version as per [GitHub's documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources). Could you confirm if this will affect the test?
