### ISSUE TITLE
How to extract more than 300 of last events?

### ISSUE THREAD

**Issue by snuyanzin** [hub4j/github-api#1628]
There is a code snippet to extract events for account.
It seems it extracts no more than 300 of events...
How can I extract more than 300?

```java
        GitHub github = new GitHubBuilder().withJwtToken("<token>").build();
        PagedIterator<GHEventInfo> it = github.getMyself().listEvents().iterator();
        while (true) {

            List<GHEventInfo> ghEventInfos = it.nextPage();
            for (GHEventInfo event: ghEventInfos) {
                /// do some logic
            }
            if (ghEventInfos.isEmpty()) {
                break;
            }
        }

```

**Comment by bitwiseman** [comment]
It think this might be limit of the API itself.  

https://docs.github.com/en/rest/activity/events?apiVersion=2022-11-28

It doesn't say the limit is 300, but it does say: 

> Only events created within the past 90 days will be included in timelines. Events older than 90 days will not be included (even if the total number of events in the timeline is less than 300).
