### ISSUE TITLE
Feature Request: Get An App by Slug, Create App from Manifest

### ISSUE THREAD

**Issue by dbaur** [hub4j/github-api#1641]
Feature Request: 

GET /apps/{app_slug}: https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-app
POST /app-manifests/{code}/conversions: https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-a-github-app-from-a-manifest

The basic implementation for an GHApp already exists, however only the endpoint retrieving the currently authorized App is supported.

If desired I could provide the implementation for both endpoints.

**Comment by dbaur** [comment]
I have implemented the code in a fork and tested it against my own account. However, to implement the final tests, I probably require access to the Test Organization.

**Comment by bitwiseman** [comment]
@dbaur  Invitation sent.
