### ISSUE TITLE
GHRepository#getPermission fails with a user having the maintain role

### ISSUE THREAD

**Issue by PierreBtz** [hub4j/github-api#1671]
**Describe the bug**
When trying to retrieve the permission of a user with the maintain role on a repository, an exception is raised:

```
java.lang.IllegalArgumentException: No enum constant org.kohsuke.github.GHPermissionType.MAINTAIN
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.kohsuke.github.GHPermission.getPermissionType(GHPermission.java:55)
	at org.kohsuke.github.GHRepository.getPermission(GHRepository.java:1096)
```

**To Reproduce**

A test reproducing the issue against the `hub4j-test` organization has been created:

https://github.com/hub4j/github-api/commit/ff26f68286ec9066114a045b45ae34747bb4cb57

**Expected behavior**

The permission is properly retrieved.

**Additional context**

The naive approach would be to add `MAINTAIN` value in the `GHPermissionType` enum but it doesn't seem right to confuse roles and permissions and [the github documentation](https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#get-repository-permissions-for-a-user) clearly lists only `admin, write, read, and none` as valid permissions.

So I think the issue is with https://github.com/hub4j/github-api/blob/29799cde73a32f923e90a6dc3f8f139c2cd56b47/src/main/java/org/kohsuke/github/GHPermission.java#L54-L56 but I'd need help figuring things out.

**Comment by stratiocommit-test** [comment]
Hi! We are facing the same error from Jenkins pipelines:
![image](https://github.com/hub4j/github-api/assets/36296135/633d5483-2bbb-492f-be67-062794ccb04a)

**Comment by lpgutierrez** [comment]
Hi! We are facing the same issue from Jenkins pipelines:
![image](https://github.com/hub4j/github-api/assets/92737780/9b1a2aac-797f-4778-bfa7-36e131dd1ec9)

**Comment by PierreBtz** [comment]
Yeah, fun fact I extracted this use case out of a failing Jenkins build :)

**Comment by jtnord** [comment]
> The naive approach would be to add MAINTAIN value in the GHPermissionType enum but it doesn't seem right to confuse roles and permissions and [the github documentation](https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#get-repository-permissions-for-a-user) clearly lists only admin, write, read, and none as valid permissions.

this is the approach?

<img width="455" alt="image" src="https://github.com/hub4j/github-api/assets/494726/e83683ac-c338-4c98-9b2c-649001611eab">

**Comment by PierreBtz** [comment]
But those permissions do not match at all the enum: https://github.com/hub4j/github-api/blob/a785a2a978de3927b4d75718be997df84d0964d9/src/main/java/org/kohsuke/github/GHPermissionType.java#L11-L18

**Comment by PierreBtz** [comment]
The enum since to match:

![Screenshot 2023-06-05 at 14 40 10](https://github.com/hub4j/github-api/assets/9881659/33923dd3-062d-4c91-a1bb-fa10a25e6cd0)

I wonder if there shouldn't be two distinct enums?

**Comment by jglick** [comment]
GitHub does version their APIs, so if they just introduced a new return value today maybe it is tied to a new version. However this client does not consistently pin a version.

**Comment by jglick** [comment]
https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#get-repository-permissions-for-a-user does currently mention `maintain`. This is still labelled

> API Version: 2022-11-28 (latest)

suggesting this was some sort of unversioned API change. OTOH https://web.archive.org/web/20230105012504/https://docs.github.com/en/rest/collaborators/collaborators does already mention `maintain`. Perhaps the docs had long supported it but it only recently began to actually be returned?

**Comment by hpsin** [comment]
:wave: Hey all. We're rolling back the changes that triggered this issue.
We found that users assigned to the base role of `triage` or `maintain` were incorrectly shown as having the permission `write` or `read` base permission. These are legacy "base roles" that are used to build both custom roles as well as `maintain` and `triage`, and we were looking to fix that bug. 

Since this is a `string` field, and not an enum, this did not trigger the breaking changes detection - but given the documentation it's reasonable that that's how folks implemented this. Further compounding the problem, the documentation failed to update, not that that would have helped avoid this breakage. 

Given the reliance on this field, we're going to undo this change and freeze the base `permission` field to be this legacy value, with a note in the documentation as well. Systems interested in the user's assigned role instead of legacy base role can see the true role assignment in `role_name`. 

Apologies this broke you, and my appreciation to the folks who got this to our attention.

**Comment by jglick** [comment]
So we may need to revert this change as well, or least the `maintain` and `triage` parts (should certainly keep the more robust enum parsing). Maybe we need to also switch from `permission` to `role_name`? But this might break in older GHE.

**Comment by Dohbedoh** [comment]
Our impacted PR build seem to work now. So the rollback seem to have fixed this.

**Comment by vasukulkarni** [comment]
shoudn't the released version of github-api-plugin use released version of github-api? we are using a 2 version old plugin but see this issue and I suspect it pulls the main branch rather than use the released version for stability.
