### ISSUE TITLE
Release 46 (v1.316) request

### ISSUE THREAD

**Issue by dougj-contrast** [hub4j/github-api#1694]
Hello,

Is there a process or request that can be made to a new release? We would like to take advantage of a feature that was merged 06/12 which was after the last v1.315 release date.

We are looking to take advantage of: https://github.com/hub4j/github-api/pull/1675 so we are looking for v1.316 to be released.

Thanks!
Doug

**Comment by bitwiseman** [comment]
@dougj-contrast 
I'll get a new release out this week.

**Comment by bitwiseman** [comment]
https://github.com/hub4j/github-api/releases/tag/github-api-1.316

**Comment by dougj-contrast** [comment]
Thanks @bitwiseman!!
