### ISSUE TITLE
GHCommentAuthorAssociation MANNEQUIN missing

### ISSUE THREAD

**Issue by HelvetiaAppDev** [hub4j/github-api#1716]
**Describe the bug**
In the enum GHCommentAuthorAssociation there can come another value that can not be parsed: MANNEQUIN 
Also see: https://docs.github.com/en/graphql/reference/enums#commentauthorassociation

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.kohsuke.github.GHCommentAuthorAssociation` from String "MANNEQUIN": not one of the values accepted for Enum class: [OWNER, FIRST_TIMER, NONE, MEMBER, CONTRIBUTOR, COLLABORATOR, FIRST_TIME_CONTRIBUTOR]
```

**To Reproduce**
Try to get revuew comments of with an unclaimed user as author.

**Expected behavior**
No error.

**Additional context**
This value is possible for migrated repositories.

**Comment by choichanhyeok** [comment]
Hi @HelvetiaAppDev ,

I'm interested in contributing this project, particularly regarding Issue #1716.Would it be alright if I worked on this issue?

Looking forward to your guidance.

Thanks,

**Comment by bitwiseman** [comment]
Go right ahead. Look at the git blame for that file and the previous change to that enum should be a good example of what this change should look like.
