### ISSUE TITLE
Unknown value startup_failure

### ISSUE THREAD

**Issue by iamironz** [hub4j/github-api#1722]
**Describe the bug**

Hey! 
It looks like `startup_failure` conclusion status has not been added yet into the library itself, but it is presented in REST API:

```
 WARNING: Unknown value startup_failure for enum class org.kohsuke.github.GHWorkflowRun$Conclusion, defaulting to UNKNOWN
```

**To Reproduce**
1. Call `listWorkflows` and filter to the one that has "failed to start" runs
2. Call `listRuns` for this instance
3. Call `withPageSize(n)` (to limit the output size) to the point where `startup_failure` is presented and `toList` 
4. Call `getConclusion` method

**Expected behavior**
No warnings on `getConclusion` method call

**Version:**
 - Library version `1.316`

**Comment by gsmet** [comment]
Looks like a good opportunity to contribute :).

**Comment by yasin-herken** [comment]
I want to work on it

**Comment by bitwiseman** [comment]
@yasin-herken  Go ahead.

**Comment by yasin-herken** [comment]
I couldn't figure out how to add workflow according to the Conclusion enum class but I added a test just in case
