### ISSUE TITLE
Proposal: New release version, as so to include the newly supported merge group events

### ISSUE THREAD

**Issue by felipefrancisco** [hub4j/github-api#1729]
On Oct 13, @bitwiseman kindly reviewed and merged https://github.com/hub4j/github-api/pull/1726 into `master`, which allows this project to support merge group events.

Given the last release of this project was on August 21, I'd like to suggest that a new release is issued and made available for other projects that use `hub4j/github-api` as a dependency (like `jenkinsci/github-plugin`), so they can benefit from the newly supported events.

**Comment by bitwiseman** [comment]
Done.
