### ISSUE TITLE
GitHub API 1.318 breaks Jenkins GitHub branch source plugin API rate limiting tests

### ISSUE THREAD

**Issue by MarkEWaite** [hub4j/github-api#1756]
**Describe the bug**

The transition from GitHub API 1.316 to GitHub API 1.318 causes the [Jenkins GitHub branch source plugin](https://plugins.jenkins.io/github-branch-source/) to fail several of its API rate limiting tests.  The failures can be seen in the plugin bill of materials attempt to build with the 1.318 GitHub API plugin, visible on the following lines:

* [Weekly](https://github.com/jenkinsci/bom/runs/19024778179)
* [2.426.x](https://github.com/jenkinsci/bom/runs/19025248485)
* [2.414.x](https://github.com/jenkinsci/bom/runs/19025700790)
* [2.401.x](https://github.com/jenkinsci/bom/runs/19026494515)

**To Reproduce**
1. Clone the [Jenkins GitHub branch source plugin](https://plugins.jenkins.io/github-branch-source/) with 
    `git clone https://github.com/jenkinsci/github-branch-source-plugin.git`
2. Change to the cloned repository with 
    `cd github-branch-source-plugin`
5. Checkout the release tag for most recent release with 
    `git checkout 1751.v90e17c48a_6a_c`
7. Confirm using the expected Java version (Java 11 for me) and maven version with `mvn -version`
    ```
    Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
    Maven home: /home/mwaite/tools/apache-maven-3.9.5
    Java version: 11.0.21, vendor: Eclipse Adoptium, runtime: /opt/jdk-11
    Default locale: en_US, platform encoding: UTF-8
    OS name: "linux", version: "4.18.0-477.27.1.el8_8.x86_64", arch: "amd64", family: "unix"
    ```
8. Confirm the API rate limit test passes with the 1.316 API using the command:
    ` mvn clean -Dtest=org.jenkinsci.plugins.github_branch_source.ApiRateLimitCheckerTest verify`
10. Update the pom.xml file of the GitHub branch source plugin to use the 1.318 library instead of 1.316
    ```
    cat > ../branch-source-use-1.318.patch <<EOF
    diff --git a/pom.xml b/pom.xml
    index a501950..cee4ec1 100644
    --- a/pom.xml
    +++ b/pom.xml
    @@ -74,6 +74,7 @@
         <dependency>
           <groupId>org.jenkins-ci.plugins</groupId>
           <artifactId>github-api</artifactId>
    +      <version>1.318-461.v7a_c09c9fa_d63</version>
         </dependency>
         <dependency>
           <groupId>org.jenkins-ci.plugins.workflow</groupId>
    EOF
    git apply ../branch-source-use-1.318.patch
    ```
11. Confirm the API rate limit test fails with the 1.318 API using the command:
    ` mvn clean -Dtest=org.jenkinsci.plugins.github_branch_source.ApiRateLimitCheckerTest verify`

**Expected behavior**

API rate limit test of GitHub branch source plugin should pass with the new GitHub API or the GitHub branch source plugin should be updated with a new release that depends on the new release of the GitHub API and adapts its tests to the new GitHub API release.

**Desktop (please complete the following information):**
 - Red Hat Enterprise Linux (same failure also visible on Jenkins CI job with Ubuntu Linux 22.04)
 - Version 8.9

**Additional context**

I don't know if the [Jenkins GitHub API plugin release 1.318-461.v7a_c09c9fa_d63](https://plugins.jenkins.io/github-api/releases/#version_1.318-461.v7a_c09c9fa_d63) breaks Jenkins interactive use cases yet.  Interactive tests are needed to explore that further.

**Comment by bitwiseman** [comment]
@MarkEWaite sorry for the inconvenience. I forgot how brittle the GHBS tests around this area are. I'll go back and update them.

**Comment by bitwiseman** [comment]
@MarkEWaite  
https://github.com/jenkinsci/github-branch-source-plugin/pull/749 This not an issue with this library but rather extremely brittle tests in GHBS.

**Comment by MarkEWaite** [comment]
Thanks very much @bitwiseman !
