### ISSUE TITLE
How to get list users that are assigned to an organization role

### ISSUE THREAD

**Issue by ishepard** [hub4j/github-api#1806]
According to GH docs ([List users that are assigned to an organization role](https://docs.github.com/en/rest/orgs/organization-roles?apiVersion=2022-11-28#list-users-that-are-assigned-to-an-organization-role)), it should be:
```
https://api.github.com/orgs/ORG/organization-roles/ROLE_ID/users
```

In GHOrganization, I see there is a function `listMembersWithRole`, but it doesn't work for this case. The endpoint seems different:
```
/orgs/{this.login}/members
``` 
and when I tried it in my organization where there are 2 Owners and 1 Member, the function returns all members.

Is there a way to get this info?
Thanks!

**Comment by ishepard** [comment]
This might be something on my side actually, I see that even when using the GH API I don't get the roles. I'll investigate further

**Comment by bitwiseman** [comment]
@ishepard 
Closing for now.  Comment and I'll reopen.
