### ISSUE TITLE
Feature Request: Handle supports for the External Groups endpoints

### ISSUE THREAD

**Issue by jbenaventem** [hub4j/github-api#1828]
## Description of the issue:

I am proposing the implementation of enterprise endpoints to manage and support external groups from an Identity Provider (IDP) within a GitHub Enterprise account. This feature would enhance the functionality of the GitHub API library by providing additional support for enterprise-level operations.

The relevant documentation can be found here: [GitHub Enterprise Cloud Documentation](https://docs.github.com/en/enterprise-cloud@latest/rest/teams/external-groups?apiVersion=2022-11-28#about-external-groups)

If there is agreement on the value of this feature, I am willing to contribute to its implementation. I believe this addition would greatly enhance the library's capabilities and provide valuable tools for managing GitHub Enterprise accounts. Thank you for considering this proposal.  I am open to discussing other potential solutions for these enterprise-associated endpoints.

Regards

**Comment by bitwiseman** [comment]
PRs welcome. You might want need to do some work to get the test coverage needed in CI.
