### ISSUE TITLE
Add support for fetching a single organisation member by username

### ISSUE THREAD

**Issue by fv316** [hub4j/github-api#1849]
Right now, fetching a single GitHub organisation member by username requires listing all members in that organisation using the `listMembers` method and filtering the response by the username. A similar approach is already encoded in the library for the `getTeamByName` which lists all teams and then filters by the team name. However, there exists a [Get Organisation Memberships For A User](https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#get-organization-membership-for-a-user) endpoint on the GitHub API that could be used to fetch the user and other useful attributes. 

This new method would be very similar to the `hasMember` method in the `GHOrganisation.class` (copied below) but calls `/orgs/{org}/memberships/{username}` and needs to map the response to the appropriate GHUser object. 

```
    /**
     * Checks if this organization has the specified user as a member.
     *
     * @param user
     *            the user
     * @return the boolean
     */
    public boolean hasMember(GHUser user) {
        try {
            root().createRequest().withUrlPath("/orgs/" + login + "/members/" + user.getLogin()).send();
            return true;
        } catch (IOException ignore) {
            return false;
        }
    }
```

I'm happy to create a PR if you think this would be valuable.

**Comment by bitwiseman** [comment]
PR with tests welcome.

**Comment by fv316** [comment]
Could you give me access to the `hub4j-test-org`?

**Comment by fv316** [comment]
Could you give me access to `hub4j-test-org`?
