### ISSUE TITLE
GHRelease.uploadAsset() does not work for Github Enterprise

### ISSUE THREAD

**Issue by lwiechec** [hub4j/github-api#266]
looking at [source code](https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GHRelease.java#L130), the URL for uploading releases is hardcoded to Gighub.com's.

I will attempt to extend it for GitHub Enteprise, using `GitHub.getApiURL()`...

**Comment by oleg-nenashev** [comment]
Yes, it's definitely a bug

**Comment by lwiechec** [comment]
@oleg-nenashev  Thanks for reply :) I was wondering what would be the good course of action; after reading [the release upload API docs](https://developer.github.com/enterprise/2.5/v3/repos/releases/#upload-a-release-asset), I think we need first to 'ask' for the upload URL (via calling GitHub's API `/repos/{user}/{repo}/releases/{id}` for `upload_url` and then use it. Would you think it's correct?

**Comment by lwiechec** [comment]
Hi, I have created a very simple fix, adding another version of `uploadAsset()` that accepts the upload URL.

**Comment by kohsuke** [comment]
Please see my comment to PR #267

**Comment by mpern** [comment]
I just stumbled across this issue, you can not upload assets to Github Enterprise

**Comment by bitwiseman** [comment]
I believe this is fixed.  

@mpern @lwiechec  if you can reproduce, please comment with how steps to reproduce.
