### ISSUE TITLE
API is not thread safe

### ISSUE THREAD

**Issue by mmitche** [hub4j/github-api#280]
Typically in Jenkins plugins, we are sharing GitHub instances to avoid lots of individual objects.  The API isn't thread safe, and while this doesn't seem to cause actual errors, it does have tendency to cause unneeded API calls.  For instance, simultaneous getUser calls for the same user may both make a call to the server before attempting to update the map.

I have some fixes in the root GitHub object around the cached maps (mostly just locking fixes), but I'd like to get an opinion on what the 'real' fix is.

Keeping separate GitHub objects isn't an option since we lose all of the caching in that approach.

**Comment by bitwiseman** [comment]
@mmitche  
I'm open to PRs if you're still around and interested.

**Comment by bitwiseman** [comment]
Closing for now.
This is still true, but a general bucket of all thread-safety work is not super helpful.  
Willing to reopen or open new issues as appropriate.
