### ISSUE TITLE
Many classes do not have toString implementations

### ISSUE THREAD

**Issue by rahulsom** [hub4j/github-api#412]
This causes weirdness in unexpected places, like this in Jenkins

<img width="1679" alt="ghteam" src="https://user-images.githubusercontent.com/193047/36124955-ef8b625e-1006-11e8-801d-e8c9fdb9f3bf.png">

**Comment by kohsuke** [comment]
`toString()` in this library is really just a debug assistance, so I'd say Jenkins is doing something wrong if it's assuming `toString()` to be something meaningful to users.

And thanks for your interest to contribute. Given the way `toString()` works, it's totally fine to just eyeball and pick up a few key fields.

Maybe this is a good opportunity to bring some consistency to the format `toString()` uses, too.

**Comment by bitwiseman** [comment]
@rahulsom 
Yes, PRs welcome.

**Comment by lwx979458** [comment]
Has the toString method been added? @rahulsom

**Comment by bitwiseman** [comment]
@lwx979458 PRs welcome.
