### ISSUE TITLE
Respect XDG Base Directory specification for dotfile location

### ISSUE THREAD

**Issue by edwardstm** [hub4j/github-api#471]
Please implement support for the XDG Base Directory specification, described [here](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). In particular, `.github` should by default be created in `$XDG_CONFIG_HOME` rather than `$HOME`. By default, this should be `$HOME/.config/` rather than the current `$HOME` path.

**Comment by bitwiseman** [comment]
It is unclear what this is asking for.  This library doesn't create directories.
