### ISSUE TITLE
GHPullRequestFileDetail seems to be returning wrong/unexpected sha

### ISSUE THREAD

**Issue by LenGillespie** [hub4j/github-api#486]
Given this groovy snippet:
```
#!/usr/bin/env groovy

import org.kohsuke.github.*

@GrabResolver(name = 'jenkins-api', root = 'http://central.maven.org/maven2')
@Grab("org.kohsuke:github-api:1.95")

String repo = "<repo>"
String apiToken = "<token>"
String organization = "<org>"
int prId = <id>

def getRepository = { repoName ->
    GitHub github = GitHub.connectUsingOAuth(apiToken)
    return github.getRepository("${organization}/${repoName}")
}

def getPullRequestChanges = { repoName, id ->
    GHPullRequest pullRequest = getRepository(repoName).getPullRequest(id)
    return pullRequest.listFiles().collect()
}

List<GHPullRequestFileDetail> changes = getPullRequestChanges(repo, prId)

changes.each {
    println "Commit: https://github.com/${organization}/${repo}/commit/${it.sha}"
}

```

I'm expecting to get the SHA where the file was changed on the branch but that doesn't seem to be the case. I can see the 6 files changed on the PR but when I navigate to any of their associated SHAs, I get a 404.

**Comment by bitwiseman** [comment]
This is by design behavior of the [GitHub API for files](https://developer.github.com/v3/pulls/#list-pull-requests-files). The file sha is not the same as the commit sha.   

It might be possible to parse the commit sha from the `raw_url` but it would be a brittle behavior.  

PRs welcome.

**Comment by t0m4uk1991** [comment]
@bitwiseman @LenGillespie 

I'm not sure GHPullRequestFileDetail should know about the commit hash, it should just represent the file that was changed in the scope of PR. Looks like we can get hash from the pull request object.

Here is the small test in java:
`package org.kohsuke.github;

import java.io.IOException;

public class SimpleTest {
    public static void main(String[] args) throws IOException {
        final String apiToken = "<placeholder>";
        final String repoName = "hub4j/github-api";
       
        final GitHub gh = new GitHubBuilder().withOAuthToken(apiToken).build();
        final GHPullRequest pullRequest = gh.getRepository(repoName).getPullRequest(1187);
        final String commitSha = pullRequest.getHead().getSha(); //SHA of the tip of the commits to merge
        System.out.println(String.format("Commit: https://github.com/%s/commit/%s", repoName, commitSha));

        pullRequest.listFiles().toList().stream().forEach(item -> {
            System.out.println(item.raw_url.contains(commitSha));
            System.out.println(item.blob_url.contains(commitSha));
            System.out.println(item.contents_url.contains(commitSha));
        });
    }
}
`

**Comment by bitwiseman** [comment]
@t0m4uk1991 
The problem being reported is that `file.getSha()` returns the SHA-1 of the file, not the SHA-1 for the commit.

The example from the docs for [GitHub API for files in a PR](https://docs.github.com/en/rest/reference/pulls#list-pull-requests-files) makes it clear this is expected behavior: 

```json
[
  {
    "sha": "bbcd538c8e72b8c175046e27cc8f907076331401",
    "filename": "file1.txt",
    "status": "added",
    "additions": 103,
    "deletions": 21,
    "changes": 124,
    "blob_url": "https://github.com/octocat/Hello-World/blob/6dcb09b5b57875f334f61aebed695e2e4193db5e/file1.txt",
    "raw_url": "https://github.com/octocat/Hello-World/raw/6dcb09b5b57875f334f61aebed695e2e4193db5e/file1.txt",
    "contents_url": "https://api.github.com/repos/octocat/Hello-World/contents/file1.txt?ref=6dcb09b5b57875f334f61aebed695e2e4193db5e",
    "patch": "@@ -132,7 +132,7 @@ module Test @@ -1000,7 +1000,7 @@ module Test"
  }
]
```

The `raw_url` shows the commit sha while `sha` is different. If there is a change here it is probably to update the JavaDoc to link to the docs page and for `getSha()` to clearly state this SHA is not the commit sha.
