### ISSUE TITLE
Metric to monitor Github API usage

### ISSUE THREAD

**Issue by pgmillon** [hub4j/github-api#524]
Hi,
In order to monitor Github API usage and prevent API rate limiting it would be great to have a simple metrics exposed.
This could be really helpful on highly used Jenkins instances that have a combination of multibranch pipelines & shared library on Github.
See: https://issues.jenkins-ci.org/browse/JENKINS-36121
Maybe something inside [Requester.buildRequest](https://github.com/kohsuke/github-api/blob/4dce17363059521f90d9b58eacd4edc434544db5/src/main/java/org/kohsuke/github/Requester.java#L408) ?

**Comment by bitwiseman** [comment]
The metrics are exposed: 
https://github.com/github-api/github-api/blob/master/src/main/java/org/kohsuke/github/GitHub.java#L317-L373

Perhaps they could be documented better.  Or are you looking for this library to implement the rate limit checking like this: https://github.com/jenkinsci/github-branch-source-plugin/blob/1c2c688b50f70da1d237065c31ec69c01d062fb9/src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java#L572

**Comment by bitwiseman** [comment]
The approach should be simpler to start with.  And then additionally we should implement a `RateLimitStrategy` class that will automatically check and attempt to throttle requests to avoid going over.  It would save clients from having to pepper their code with `checkRateLimit()` everywhere.

**Comment by bitwiseman** [comment]
#601

**Comment by bitwiseman** [comment]
Also added a RateLimitChecker extension point to the API.
