### ISSUE TITLE
assets on GHRelease

### ISSUE THREAD

**Issue by johnoliver** [hub4j/github-api#528]
The github api returns a list of assets from the releases endpoint (see https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository). This data is ignored when the api data is deserialized due to `GHRelease` not containing an `assets` field. This leads to requiring making additional api calls, one for every release in order to obtain asset information.

A quick test of adding `List<GHAsset> assets;` to `GHRelease` worked and the api data was correctly parsed into the assets field. I am happy to pull request this change, however this would change the current behaviour to some extent, at the moment every time `GHRelease.getAssets` is called a fresh list of assets is requested from the api. If we were to add `List<GHAsset> assets;` to `GHRelease` this would mean that a set of assets would be cached when the `GHRelease` is created and would remain unchanged even if upstream is updated. The correct behaviour for `GHRelease.uploadAsset` would also need to be determined.

Would this be viewed as acceptable behaviour?

This is quite a significant issue as it produces an unnecessary api call to request data that has already been provided, potentially hitting rate limits.

**Comment by bitwiseman** [comment]
@johnoliver 
Having a local list of assets doesn't seem horrible.  You could even have the list start as null and only populate it when someone call `getAssets()`.  

However, if your main concern is reducing rate-limit usage, you should look at using the `OkHttpConnector` and adding a cache to your `OkHttpClient`.  That will get you the desired behavior, up-to-date information without using up your rate-limit budget.

**Comment by skaldarnar** [comment]
I'd like to upvote the proposal to include `List<GHAsset> assets` as the regular caching (based on the `etag` Github sends with each response) does not help here. The underlying problem is that one needs to make _n + 1_ calls for _n_ releases (at least) to get the asset URLs for each release - although they are present in the response (see https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-releases).
