### ISSUE TITLE
Exceptions defined in shaded dependencies break exception catching in clients

### ISSUE THREAD

**Issue by bitwiseman** [hub4j/github-api#677]
We added a shaded artifact in #630 to try to make this library "more portable".  It turns out this is not a drop-in replacement.  

All classes defined in one of the shaded dependencies are relocated to a new `hidden` package to avoid conflicts. This includes exceptions. This means any consumer of this library that wants to specifically catch `com.fasterxml.jackson.databind.JsonMappingException` from the shaded library (as opposed to a general `java.io.IOException`) would would need to be rewritten to catch `hidden.com.fasterxml.jackson.databind.JsonMappingException`. 

The only alternative to this is to define our own exceptions based on those in shaded exceptions and rethrow with them.  That would end up being a whack-a-mole finding all exceptions that might be thrown and in any case would still be a breaking change. 

I'm inclined to give up on shading entirely.

**Comment by oleg-nenashev** [comment]
> That would end up being a whack-a-mole finding all exceptions that might be thrown and in any case would still be a breaking change.

It is quite easy for Checked exceptions though API changes also mean the breaking compatibility changes. For unchecked ones... you rather do not want them in an API library.

**Comment by bitwiseman** [comment]
@oleg-nenashev  
I'm not sure I understand your point.

**Comment by bitwiseman** [comment]
I removed shading in this commit:  https://github.com/github-api/github-api/commit/c8115b1c10d62379459e9da64bd588fd2115c376

If someone cares about this enough to redo it at some point, they can.
