### ISSUE TITLE
`GHRepository.enableProjects()` does not update `has_projects`

### ISSUE THREAD

**Issue by bitwiseman** [hub4j/github-api#765]
**Describe the bug**
`GHRepository.enableProjects()` does not update `has_projects`.  The value is sent github reports success, but the value is not changed.

**Comment by sladyn98** [comment]
Looks like an upstream error

**Comment by bitwiseman** [comment]
@sladyn98 
Turns out `"true"` is not the same as `true`.  We were sending `"true"` and for other fields it would autoconvert to `true`, but `has_projects` was expecting `true` or `false` with no conversion.
