### ISSUE TITLE
Private repo always hasWiki()

### ISSUE THREAD

**Issue by Katsute** [hub4j/github-api#784]
**Describe the bug**
Private repositories always return `true` for `hasWiki()` even if they have none enabled.

**To Reproduce**
Use `GHRepository#hasWiki()` on a private repository with wikis disabled.

**Expected behavior**
`hasWiki()` should return false for private repositories with wikis disabled.

**Desktop (please complete the following information):**
- Windows 10
- API 1.110

**Additional context**
This issue may be caused by the fact that private repositories can not have public wikis (meaning the tickbox is technically *disabled* instead of deselected).

**Comment by bitwiseman** [comment]
I have a private repository with a wiki.  I can also disable and enable wikis on that repo.  

This is almost certainly an external issue that should be reported to GitHub support.  Double check the data being return from the GitHub API.

**Comment by Katsute** [comment]
For free users public wikis are disabled on private repositories.

**Comment by Katsute** [comment]
GitHub Suppport is now addressing this issue.
