### ISSUE TITLE
Need support for "Updating the pull request branch with latest upstream changes"

### ISSUE THREAD

**Issue by prabinb** [hub4j/github-api#787]
Currently there is no way to update the pull request with the latest upstream changes, when using the library. Github has provided a REST endpoint for it - https://developer.github.com/v3/pulls/#update-a-pull-request-branch

It will be good use case to add to the library.

**Comment by bitwiseman** [comment]
Cool. It looks like it is in preview so the implementer will need to use the Preview API structures [like this](https://github.com/github-api/github-api/commit/5cb6bfa633ea40af49e3a148a37a4beaf0a1de06#diff-d7bd0631e27e71e0361fe497cc44e5baR522-R525) using `@Preview @Deprecated` attributes. Other than that seems like something anyone with the time can do.
