### ISSUE TITLE
getRef method bug

### ISSUE THREAD

**Issue by hipporello** [hub4j/github-api#794]
**Describe the bug**
gitRef method uses wrong api end point. It causes a deserialization problem. It should use `git/ref/%d` instead of `git/ref/%s`.

**Comment by bitwiseman** [comment]
@hipporello  
Which class's `getRef()` method? Please provide more details.

**Comment by hipporello** [comment]
Hi,

It is GHRepository class and the method signature is:

public GHRef getRef(String refName) throws IOException {

**Comment by bitwiseman** [comment]
@hipporello 
Why should it use `git/ref/%d`?  
Please provide and example where `git/ref/%s` does not work correctly.

**Comment by hipporello** [comment]
Hi,

You are using git/refs/%s currently for getRef method of GHRepository. This brings all matching references instead of a single ref value which I expect getRef should return. Instead of git/refs/%s, you should use git/ref/%s. This will bring exactly specified reference.

**Comment by bitwiseman** [comment]
So, the problem isn't `%s` but rather `refs` vs `ref`?  I see.

Here are four queries and the response from them:

* [git/refs/heads/gh-pages](https://api.github.com/repos/hub4j/github-api/git/refs/heads/gh-pages)
* [git/ref/heads/gh-pages](https://api.github.com/repos/hub4j/github-api/git/ref/heads/gh-pages)
* [git/refs/heads](https://api.github.com/repos/hub4j/github-api/git/refs/heads)
* [git/ref/heads](https://api.github.com/repos/hub4j/github-api/git/ref/heads)

### [git/refs/heads/gh-pages](https://api.github.com/repos/hub4j/github-api/git/refs/heads/gh-pages)

```json
{
  "ref": "refs/heads/gh-pages",
  "node_id": "MDM6UmVmNjE3MjEwOmdoLXBhZ2Vz",
  "url": "https://api.github.com/repos/hub4j/github-api/git/refs/heads/gh-pages",
  "object": {
    "sha": "bf902ab5c8aade1e5cbefa6db4cf39f5f3692552",
    "type": "commit",
    "url": "https://api.github.com/repos/hub4j/github-api/git/commits/bf902ab5c8aade1e5cbefa6db4cf39f5f3692552"
  }
}
```
### [git/ref/heads/gh-pages](https://api.github.com/repos/hub4j/github-api/git/ref/heads/gh-pages)

Identical to [git/refs/heads/gh-pages](https://api.github.com/repos/hub4j/github-api/git/refs/heads/gh-pages) above.

### [git/refs/heads](https://api.github.com/repos/hub4j/github-api/git/refs/heads)

```json
[
  {
    "ref": "refs/heads/gh-pages",
    "node_id": "MDM6UmVmNjE3MjEwOmdoLXBhZ2Vz",
    "url": "https://api.github.com/repos/hub4j/github-api/git/refs/heads/gh-pages",
    "object": {
      "sha": "bf902ab5c8aade1e5cbefa6db4cf39f5f3692552",
      "type": "commit",
      "url": "https://api.github.com/repos/hub4j/github-api/git/commits/bf902ab5c8aade1e5cbefa6db4cf39f5f3692552"
    }
  },
  {
    "ref": "refs/heads/master",
    "node_id": "MDM6UmVmNjE3MjEwOm1hc3Rlcg==",
    "url": "https://api.github.com/repos/hub4j/github-api/git/refs/heads/master",
    "object": {
      "sha": "dbd20fe396e13f7f6b7de5d6dfcbd9e6d8775129",
      "type": "commit",
      "url": "https://api.github.com/repos/hub4j/github-api/git/commits/dbd20fe396e13f7f6b7de5d6dfcbd9e6d8775129"
    }
  }
]
```

### [git/ref/heads](https://api.github.com/repos/hub4j/github-api/git/ref/heads)

```json
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/git/refs/#get-a-single-reference"
}
```

**Comment by bitwiseman** [comment]
Having looked a bit more into this, the library has a `getRefs()` and a `listRefs()` methods (which as expected call into the `git/refs` endpoint). If someone expected something other than exactly one `GHRef` they would use those methods.  So, at first glance it seems like this will produce some kind of change in behavior, but it is probably a good change to make. 

## Questions 

Let's say we have two input ref path specifiers: `heads/gh-pages` and `heads`. 

* What is currently returned from GitHub API `git/ref` vs. `git/refs` for each input? 
* What behavior does each input currently produce from this library when `getRef()` is called?  
* How does the behavior change if we change from `git/refs/%s` to `git/ref/%s`? 


## GitHub API `git/ref` vs. `git/refs`

Here are four queries and the response from them:

* [git/refs/heads/gh-pages](https://api.github.com/repos/hub4j/github-api/git/refs/heads/gh-pages)
* [git/ref/heads/gh-pages](https://api.github.com/repos/hub4j/github-api/git/ref/heads/gh-pages)
* [git/refs/heads](https://api.github.com/repos/hub4j/github-api/git/refs/heads)
* [git/ref/heads](https://api.github.com/repos/hub4j/github-api/git/ref/heads)

### [git/refs/heads/gh-pages](https://api.github.com/repos/hub4j/github-api/git/refs/heads/gh-pages)

```json
{
  "ref": "refs/heads/gh-pages",
  "node_id": "MDM6UmVmNjE3MjEwOmdoLXBhZ2Vz",
  "url": "https://api.github.com/repos/hub4j/github-api/git/refs/heads/gh-pages",
  "object": {
    "sha": "bf902ab5c8aade1e5cbefa6db4cf39f5f3692552",
    "type": "commit",
    "url": "https://api.github.com/repos/hub4j/github-api/git/commits/bf902ab5c8aade1e5cbefa6db4cf39f5f3692552"
  }
}
```
### [git/ref/heads/gh-pages](https://api.github.com/repos/hub4j/github-api/git/ref/heads/gh-pages)

Identical to [git/refs/heads/gh-pages](https://api.github.com/repos/hub4j/github-api/git/refs/heads/gh-pages) above.

### [git/refs/heads](https://api.github.com/repos/hub4j/github-api/git/refs/heads)

```json
[
  {
    "ref": "refs/heads/gh-pages",
    "node_id": "MDM6UmVmNjE3MjEwOmdoLXBhZ2Vz",
    "url": "https://api.github.com/repos/hub4j/github-api/git/refs/heads/gh-pages",
    "object": {
      "sha": "bf902ab5c8aade1e5cbefa6db4cf39f5f3692552",
      "type": "commit",
      "url": "https://api.github.com/repos/hub4j/github-api/git/commits/bf902ab5c8aade1e5cbefa6db4cf39f5f3692552"
    }
  },
  {
    "ref": "refs/heads/master",
    "node_id": "MDM6UmVmNjE3MjEwOm1hc3Rlcg==",
    "url": "https://api.github.com/repos/hub4j/github-api/git/refs/heads/master",
    "object": {
      "sha": "dbd20fe396e13f7f6b7de5d6dfcbd9e6d8775129",
      "type": "commit",
      "url": "https://api.github.com/repos/hub4j/github-api/git/commits/dbd20fe396e13f7f6b7de5d6dfcbd9e6d8775129"
    }
  }
]
```

### [git/ref/heads](https://api.github.com/repos/hub4j/github-api/git/ref/heads)

```json
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/git/refs/#get-a-single-reference"
}
```

## Current `github-api` behavior using `git/refs`

TODO

## New `github-api` behavior using `git/ref`

TODO

**Comment by bitwiseman** [comment]
Turns out there's a reason why this was not done: it breaks GHE 2.18 and earlier, possibly later as well.
