### ISSUE TITLE
NullPointerException when a Repository has an unclear license

### ISSUE THREAD

**Issue by carlspring** [hub4j/github-api#797]
**Describe the bug**

When a repository has a license type that is unclear, such as a mixture of licenses, or is identified as `Other`, the `GHLicense`'s fields aren't properly parsed/populated and this causes `NullPointerException`-s.

An example of such a repository is https://github.com/bndtools/bnd/ . In this case, the project is under multiple license and it appears they're all in the same license file.

Code:
```
GitHub gitHub = GitHub.connectAnonymously();
GHRepository repository = gitHub.getRepository(repositoryId);

GHLicense ghLicense = repository.getLicense();

System.out.println(ghLicense.getName());

if (ghLicense.getUrl() != null)
// Without this null check, this will also throw a NullPointerException
// as the one shown below:
{
    System.out.println(ghLicense.getUrl().toString());
}

License license = new License(ghLicense.getName(),
                              ghLicense.getDescription(), // This throws a NullPointerException
                              ghLicense.getUrl().toString);  // This also throws a NullPointerException

```

Exception:
```
Exception in thread "main" java.lang.NullPointerException
	at org.kohsuke.github.GitHubRequest$Builder.withUrlPath(GitHubRequest.java:608)
	at org.kohsuke.github.GHLicense.populate(GHLicense.java:202)
	at org.kohsuke.github.GHLicense.getDescription(GHLicense.java:114)
```

**Expected behavior**

This should be error-proofed and not crash.

**Comment by carlspring** [comment]
@bitwiseman ,

Any ideas how this could be fixed? Does it look like an easy bug, or is there more to it?

**Comment by carlspring** [comment]
Also, it seems that you don't really support all the fields returned:
```json
{
  ...
  "license": {
    "key": "other",
    "name": "Other",
    "spdx_id": "NOASSERTION",
    "url": null,
    "node_id": "MDc6TGljZW5zZTA="
  },
  ...
}
```

The SPDX identifier is quite important and could be parsed by various tools.

**Comment by carlspring** [comment]
Any updates? :)

**Comment by bitwiseman** [comment]
@carlspring  
I'm not sure what the exact right fix would be.  Let's see...

`GHLicense` assumes that `url` not be null when going to get the description.  Without `url` the license and its description can't be retrieved fully.

Hm. Oh, but the method being called assumes there is one license.  It is meant to get the content of the `LICENSE` file.  Based on https://developer.github.com/v3/licenses/#get-the-contents-of-a-repositorys-license , it uses a ruby gem to try to guess the license for this repository and can't do it. So, it is not surprising that gets confused by https://github.com/bndtools/bnd/blob/master/LICENSE . 

These methods retrieve the content and license from github and then give you either the content or license, depending on what you're asking for: 

https://github.com/github-api/github-api/blob/7d842175f7984e33b3d97346cba3b20a1f905031/src/main/java/org/kohsuke/github/GHRepository.java#L1765-L1791

So, `ghLicense.getUrl()` can return null. At minimum, `GHLicense.populate()` should be updated to check for the `url` field being `null`.

Beyond that... If you call `toString()` on a method that returns `null`, that is not this libraries' fault.  

This bug brings up a more general issue, which I will file separately.  

@carlspring  
Would you be willing to fix this issue and add a test for it?

**Comment by carlspring** [comment]
@bitwiseman ,

Thanks for your comments!

I had a look at your API and I was hoping I'd be able to fix it, but this is not the case. If you know to fix it and have the time, this would be much appreciated.

**Comment by carlspring** [comment]
@bitwiseman ,

Will #820 fix this? When do you think you'll be able to cut a release?

**Comment by bitwiseman** [comment]
Within a week.

**Comment by carlspring** [comment]
Thank you very much! :)
