### ISSUE TITLE
getRateLimit() ignores header rate limit

### ISSUE THREAD

**Issue by bsfarrell** [hub4j/github-api#802]
**Describe the bug**
I use a GitHub Enterprise instance that does not support the `/rate_limit` endpoint (it returns a 404 error) but it _does_ return `X-RateLimit` headers.

`org.kohsuke.github.GitHubClient#getRateLimit` only checks the `/rate_limit` endpoint, and thus returns an "unknown" rate limit in this case, even though there is a configured rate limit, causing the client to potentially exceed that limit.

To add insult to injury, on our GHE instance calls to `/rate_limit` count against our rate limit, so we exceed the limit that much faster. 😄 I believe there are plans to address this, but I don't know the timeframe.

**Expected behavior**
`org.kohsuke.github.GitHubClient#getRateLimit` should return valid rate limit information if the server supports either the `/rate-limit` endpoint or the `X-RateLimit` headers.

Ideally the client would cache the knowledge of whether the `/rate_limit` endpoint is available, and fall back to exclusively using the headers in this case.

**Comment by timja** [comment]
@bsfarrell what version of github enterprise?

**Comment by bsfarrell** [comment]
2.19.13 currently.

**Comment by timja** [comment]
Do you have rate limiting turned on? https://help.github.com/en/enterprise/2.19/admin/installation/configuring-rate-limits#enabling-rate-limits-for-the-github-enterprise-server-api

**Comment by bsfarrell** [comment]
Rate limiting is done via a custom implementation- the `/rate_limit` endpoint return a 404 error indicating rate limiting is not enabled, but all requests contain `-X-rate-limit` headers that can be used to determine the remaining limit and reset time.

Ideally our custom implementation would also implement the `/rate_limit` endpoint, but that's beyond my control.

I ran into this issue due to some changes in the Jenkins github-branch-source plugin that was previously calling `GitHubClient#rateLimit()`, which worked fine with our GHE because it checked the headers, but is now calling `GitHubClient#getRateLimit()`, which doesn't.

**Comment by timja** [comment]
> Rate limiting is done via a custom implementation- the `/rate_limit` endpoint return a 404 error indicating rate limiting is not enabled, but all requests contain `-X-rate-limit` headers that can be used to determine the remaining limit and reset time.
> 
> Ideally our custom implementation would also implement the `/rate_limit` endpoint, but that's beyond my control.
> 
> I ran into this issue due to some changes in the Jenkins github-branch-source plugin that was previously calling `GitHubClient#rateLimit()`, which worked fine with our GHE because it checked the headers, but is now calling `GitHubClient#getRateLimit()`, which doesn't.

Doesn't github-branch-source have a configuration option to disable rate limiting would that help?

**Comment by bsfarrell** [comment]
I don't think so, but in any case, we _want_ the rate limiting.  The current issue is that the plugin exceeds the rate limit while scanning a repository with a large number of branches because `GitHubClient#getRateLimit()` returns an "unknown" limit, and the client doesn't throttle itself.

**Comment by timja** [comment]
> I don't think so, but in any case, we _want_ the rate limiting. The current issue is that the plugin exceeds the rate limit while scanning a repository with a large number of branches because `GitHubClient#getRateLimit()` returns an "unknown" limit, and the client doesn't throttle itself.

Just to clarify though, you've implemented custom rate limiting?

Why can't you use the built in one? (from what I can tell your version should support it)

**Comment by bsfarrell** [comment]
The team that administers our instance implemented a custom rate limiter.  I'm just a user.  I don't have any visibility into why we don't use the built-in limiting, but I assume there are probably good reasons.

I agree that ideally we'd just use the built-in rate limiting implementation, or modify our custom implementation to be indistinguishable from this library's perspective.  (I think there are some vague plans to do the latter.)  In the meantime, I'm hoping this library could make use of the rate limit headers if they're present and `/rate_limit` returns 404.

**Comment by bitwiseman** [comment]
@timja 
This is an easy fix.  Basically, if the headers contain a rate limit we should return that even if the `/ratelimit` returns a 404.  I think we can do this without breaking anything.

**Comment by bitwiseman** [comment]
Fun fact:
The header rate limit information is specific to the endpoint.  
Query: 

```
https://api.github.com/search/repositories?q=tetris+language:assembly&sort=stars&order=desc
``` 

followed by 

```
https://api.github.com/users/bitwiseman
```

You will get you two different sets of information.  The quick fix for this is to ignore this fact.  However, someone does a search query and then calls `getRateLimit()`, the quick fix would result in them getting the `search` rate limit in place of the `core` rate limit they expect.  

Of course, this could happen currently to anyone using `ratelimit()` as well, so it wouldn't be a massive regression to do the same from `getRateLimit()` in the case that it gets a 404, but just means that it wouldn't actually solve the problem of incorrect information being returned from `getRateLimit()` in all cases.  It would still be an improvement over returning `unknown` and would address the issue reported here for the most common cases.

**Comment by bitwiseman** [comment]
Ah, not so bad.  We actually protect against the search rate limit problem: 

https://github.com/hub4j/github-api/blob/85c44b352958bf6d81b74ab8b21920f1d313a287/src/main/java/org/kohsuke/github/GitHubClient.java#L501-L504
