### ISSUE TITLE
Missing api for fetching child teams

### ISSUE THREAD

**Issue by alexanderkjall** [hub4j/github-api#846]
**Describe the bug**

This is a feature request rather than a bug, but bug report was the only available option.

The github api have the possibility to fetch what child teams are part of a team:

https://developer.github.com/v3/teams/#list-child-teams

But the GHTeam class doesn't have any way to obtain such a list

**To Reproduce**
N/A

**Expected behavior**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by bitwiseman** [comment]
@alexanderkjall 
Would you like to implement this?

**Comment by alexanderkjall** [comment]
I'll give it a try.

**Comment by bitwiseman** [comment]
@alexanderkjall  Drop by the gitter.im channel if you need to chat about anything.

**Comment by alexanderkjall** [comment]
Here is a first attempt: https://github.com/hub4j/github-api/pull/849
