### ISSUE TITLE
GHCommit::ShortInfo::GHAuthor.getDate() returns null

### ISSUE THREAD

**Issue by liangzhang10748** [hub4j/github-api#883]
**Describe the bug**
After getting commits from github.getRepository(repo).listCommits()
commit.getCommitShortInfo().getAuthor().getDate() returns null

**To Reproduce**
Use the following partial example code:

            Iterator commitIterator = github.getRepository(repo).listCommits().iterator();
            while (commitIterator.hasNext()) {
                GHCommit commit = (GHCommit) commitIterator.next();
                logger.info("Checking commit: {}", commit.getSHA1());
                logger.info("Checking commit date: {}", commit.getCommitShortInfo().getAuthor().getDate());
                }
            }

The date always print out as null

Checking commit: 00e40ec77ffe8d6ecc328719add6577cc2496f85
Checking commit date: null

**Expected behavior**
Commit date should be a actual date object like

Checking commit: 00e40ec77ffe8d6ecc328719add6577cc2496f85
Checking commit date: Tue Jun 30 17:20:50 GMT 2020

**Desktop (please complete the following information):**
 - OS:
CentOS Linux release 7.7.1908 (Core)
KERNEL 3.10.0-1062.12.1.el7.x86_64

 - Version: github-api v1.113

**Additional context**
This trace back to the code comments in https://github.com/hub4j/github-api/blob/3b0216b0234eb093049fdb9afdd4da1aadc4ad8f/src/main/java/org/kohsuke/github/GitUser.java#L41

I believe there is a bug in this code: 
https://github.com/hub4j/github-api/blob/3b0216b0234eb093049fdb9afdd4da1aadc4ad8f/src/main/java/org/kohsuke/github/GHCommit.java#L122

A private member with the same name is already defined in base class
https://github.com/hub4j/github-api/blob/3b0216b0234eb093049fdb9afdd4da1aadc4ad8f/src/main/java/org/kohsuke/github/GitUser.java#L18

When calling the get function from the base class
https://github.com/hub4j/github-api/blob/3b0216b0234eb093049fdb9afdd4da1aadc4ad8f/src/main/java/org/kohsuke/github/GitUser.java#L44

It gets GitUser.date instead of GHAuthor.date and GitUser.date is null

This is a working example:
https://github.com/hub4j/github-api/blob/a42305dd59f0be426f0c9091748e947f60d76bcd/src/main/java/org/kohsuke/github/GHPullRequestCommitDetail.java#L53
Authorship.getDate() works. I believe GHAuthor should not define its own date

**Comment by liangzhang10748** [comment]
commit.getCommitShortInfo().getAuthor().getDate() used to work back in github-api v1.72. The bug started to appear when I updated the library version to v113

**Comment by bitwiseman** [comment]
@liangzhang10748 
Great analysis, thanks!  
This will make it easy to fix.

**Comment by lower-case** [comment]
Hi @bitwiseman I've raised a PR for this fix. I'm new to this project.
Please review the fix and help If I've missed something.

Thanks 😊
