### ISSUE TITLE
NullPointerException when retrieving latest release from the repository without releases 

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [hub4j/github-api#889]
**Describe the bug**

GHRelease throws NullPointerException when I call getLatestRelease() on the repository without releases.

**Expected behavior**

I expect a clearer and more user-friendly way to inform users about the results in this situation.

There are a few common ways to deal with this kind of situation, so here are my suggestions:
1. Return an Optional, that can contain or not contain the latest release.
2. Return null if the latest release is not found.
3. Throw a custom Exception and provide a short message informing that the requested repository hasn't had any releases yet.

Library version: 1.114

**Comment by bitwiseman** [comment]
@AnastasiiaSergienko 
Could you provide a call stack? It is unclear where this would occur inside this method:

https://github.com/hub4j/github-api/blob/580f2537f2b6dfa73792cd488cbf7f08b532b63b/src/main/java/org/kohsuke/github/GHRepository.java#L504-L510

**Comment by gastaldi** [comment]
I tried in my repository with no releases and the API returns null (option 2). I think this issue can be safely closed.
