### ISSUE TITLE
GHBranchProtection::RequiredReviews.getRequiredReviewers() always return 0

### ISSUE THREAD

**Issue by liangzhang10748** [hub4j/github-api#890]
**Describe the bug**
When running the API with owner privilege, it does not seem to work properly and always return 0 regardless of what the actual required approving required is set to.

**To Reproduce**
To reproduce the problem.
1. As a repo owner, enable Branch Protection and configure required approving required to 1 or more
2. Use repo owner token to log in and run the following code with Owner privilege on github,

GHRepository ghrepo = github.getRepository(repo);
GHBranch ghbranch = ghrepo.getBranch(branch);
GHBranchProtection protection = ghbranch.getProtection();
RequiredReviews requiredReviews = protection.getRequiredReviews();
int reviewers = requiredReviews.getRequiredReviewers(); 

The call succeeded without exception, but reviewers is always 0

**Expected behavior**
The API should return the actual required approving review numbers as configured in github repository

**Desktop (please complete the following information):**
 - OS: Centos 7
 - Version: github-api v1.113

**Additional context**
I suspect request heading is not configured correctly when trying to retrieve this property.
According to github api branch protection documentation: https://developer.github.com/v3/repos/branches/#get-branch-protection
A special header "application/vnd.github.luke-cage-preview+json" must be used to retrieve the number of approving pull request. But request builder for GHBranchProtection does not seem to handle it.
This is an existing example on how to handled this in GHBranchProtectionBuilder :
https://github.com/hub4j/github-api/blob/6bc617c488e96ea4e8040b54754f13ec68356bbe/src/main/java/org/kohsuke/github/GHBranchProtectionBuilder.java#L355,L357

Please investigate if it can be done for GHBranchProtection as well

**Comment by bitwiseman** [comment]
@liangzhang10748 
It sounds like you already have done more of the investigation.  Perhaps you could submit a PR with a test that fixes?

**Comment by liangzhang10748** [comment]
@bitwiseman Yes. I will follow up in a couple weeks on the fix.
