### ISSUE TITLE
Allow merging arbitrary branches of a repository

### ISSUE THREAD

**Issue by JKalash** [hub4j/github-api#905]
From what I can see, the only way to merge a branch onto another is to go via an open pull request. Have you considered implementing the following [v3 Merging API](https://developer.github.com/v3/repos/merging/) ? It takes a base branch name as parameter and a HEAD (branch name or SHA1) with a commit message and merges a branch onto another. Would be really useful.

**Comment by bitwiseman** [comment]
PRs welcome!

**Comment by JKalash** [comment]
@bitwiseman thanks! PR above 😄

**Comment by JKalash** [comment]
hey @bitwiseman thank you for taking care of this. Any plans on releasing a version soon?

**Comment by bitwiseman** [comment]
@JKalash 
Within the week.
