### ISSUE TITLE
Add support for commit signing?

### ISSUE THREAD

**Issue by agathish** [hub4j/github-api#916]
I am trying to sign commits using a GPG key. Is it possible to add support for commit signing?
The key should ideally be stored in externally. eg: ~/.github file used to store credentials.

**Comment by bitwiseman** [comment]
We can read the [`GHVerification` ](https://github.com/hub4j/github-api/blob/master/src/main/java/org/kohsuke/github/GHVerification.java) from an existing commit.  

When creating a commit via the [GitHub API](https://developer.github.com/v3/git/commits/#create-a-commit) a `signature` can be passed. All that needs to be done is adding the a method to the [`GHCommitBuilder`](https://github.com/hub4j/github-api/blob/master/src/main/java/org/kohsuke/github/GHCommitBuilder.java) to take a signature.  

I would suggest the method be  something like `withSignature(String)`.  Then callers could provide that string from where ever.
