### ISSUE TITLE
Error parsing commit timestamp

### ISSUE THREAD

**Issue by Xterminatorz** [hub4j/github-api#917]
**Describe the bug**
Getting a commit date can fail due to a parsing error

**To Reproduce**
1. Search for a commit
2. Call `commit.getCommitDate()`

**Expected behavior**
Return a Date object

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 10

**Additional context**

`java.lang.IllegalStateException: Unable to parse the timestamp: 2020-08-05T08:29:52.000-07:00
	at org.kohsuke.github.GitHubClient.parseDate(GitHubClient.java:664) ~[github-api-1.115.jar:na]
	at org.kohsuke.github.GHCommit$ShortInfo.getCommitDate(GHCommit.java:85) ~[github-api-1.115.jar:na]
	at org.kohsuke.github.GHCommit.getCommitDate(GHCommit.java:440) ~[github-api-1.115.jar:na]`

**Comment by bitwiseman** [comment]
@Xterminatorz 
Is the commit you're trying to look at public?  
Are you point this at `github.com` or at a local GitHub Enterprise server?  If GitHub Enterprise, what version?

**Comment by Xterminatorz** [comment]
We are using GitHub Enterprise Server 2.20.11.

**Comment by bitwiseman** [comment]
@Xterminatorz 
Strange. Can you share to commit you're working with?

**Comment by Xterminatorz** [comment]
I don't think there's a way for me to share the commit. I was thinking the timestamp in the stack trace was enough information. I believe this format just needs to be added to the TIME_FORMATS array: `"yyyy-MM-dd'T'HH:mm:ss.SSSXXX"`.
