### ISSUE TITLE
GHRepository's isPrivate() returns true for Internal repositories

### ISSUE THREAD

**Issue by subashiniunny** [hub4j/github-api#932]
We see that isPrivate() method in GHRepository class returns true for Internal repositories too. We tried this with the latest version 1.116 of the API. 
We want to be able to distinguish between private and internal repositories. 
Is this possible with the current API?

**Comment by bitwiseman** [comment]
The `internal` repository type is new and has not been added yet. `"private": true` is what GitHub is returning. This is a reasonable statement - the repository is not public. `internal` can be thought of as "private to this enterprise account". 

https://developer.github.com/changes/2019-12-03-internal-visibility-changes/

The visibility field is part of the `nebula` preview.

**Comment by subashiniunny** [comment]
I understand the "private to this enterprise account" part. But it is still different from a truly "private" repo. 
Is there a way for the API to distinguish between the two?

**Comment by bitwiseman** [comment]
@subashiniunny 
It can be done, but it is not done currently.  The correct behavior is to add a `getVisibilty()` method to `GHRepository` and to guard the visibility field with a `populate` or `refresh` call.

**Comment by lower-case** [comment]
Hi @bitwiseman 
I've raised a Draft PR for this issue. I'm working on the tests. 
Would love to hear any feedback/review from your side.

Thanks 😊

**Comment by gzuccarelli** [comment]
Hi! Any update on this?

**Comment by bitwiseman** [comment]
@gzuccarelli  Waiting for @lower-case  to have time to finish this.  If you have time, you are welcome to submit a PR that addresses the feedback.

**Comment by nvahren** [comment]
I took a swing at this in https://github.com/hub4j/github-api/pull/1074, if you would like to review.
