### ISSUE TITLE
Expose ETag and Status when getting file contents

### ISSUE THREAD

**Issue by AlexShtarbev** [hub4j/github-api#940]
## Use-case
In [HubSpot](https://www.hubspot.com/products/get-started-f049?utm_id=403967777216&utm_medium=paid&utm_source=google&utm_term=Marketing_hubspot_EN&utm_campaign=Marketing_MQLs_EN_AdWords_EMEA_UKI_Brand-HubSpot_e_c_856706782_403967777216&hsa_tgt=kwd-298569398281&hsa_grp=45114446858&hsa_src=g&hsa_net=adwords&hsa_mt=e&hsa_ver=3&hsa_ad=403967777216&hsa_acc=2734776884&hsa_kw=hubspot&hsa_cam=856706782&gclid=CjwKCAjwkoz7BRBPEiwAeKw3q8tdZM84jdkkSpI_XrEiBEiM-JZ04c-f71Ve37oLov8A-PMFSUwefxoCxyQQAvD_BwE) we use the `github-api` and are very happy with the implementation. To reduce the load the to requests sent to `GitHub` and `GitHub:Enterprise` [contents](https://docs.github.com/en/rest/reference/repos#contents) API we would like to use the `ETag` to store contents of files in a `persistent key-value` store where the `key` is contains the ETag and the `value` is the contents of the file. This is meant to be an implementation that extends beyond the standard 60 seconds HTTP cache provided by OkHttp. 

So, when we want to get the contents of a file we will add the ETag to the Request headers. In the response, if the ETag matches, we will get a 304 and empty file contents. If not - we will get the response as usual.

## Request
Would it be possible to somehow expose ETag when getting file contents. Perhaps even in the `GHContent` object itself? Or maybe have a method dedicated to returning a completely new object that contains both the current `GHContent`, the `status code` and a field for the `ETag`? With that said, would it also be possible to have an `ETag` parameter be added to a method so that the ETag can be included in Request headers?

**Comment by bitwiseman** [comment]
@AlexShtarbev 

Have you tried using [`okhttp3.OkHttpConnector()`](https://github.com/hub4j/github-api/blob/master/src/main/java/org/kohsuke/github/extras/okhttp3/OkHttpConnector.java) with a [cache set on the client](See https://square.github.io/okhttp/caching/)?  That cache is not time based but size based. I think it does exactly what you want without you having to manage ETag and contents yourself.  (The time setting you're talking about is part of the request headers and is handled as well.) 

Take a look at this test https://github.com/hub4j/github-api/blob/master/src/test/java/org/kohsuke/github/extras/okhttp3/OkHttpConnectorTest.java to see this working.

**Comment by bitwiseman** [comment]
@AlexShtarbev I'm going to close this for now, you are welcome to reopen if needed.
