### ISSUE TITLE
Use of deprecated APIs in documentation without listing an alternative

### ISSUE THREAD

**Issue by hemeroc** [hub4j/github-api#961]
**Describe the bug**
The [documentation of how to authenticate as an app
](https://github-api.kohsuke.org/githubappappinsttokenauth.html) contains calls to deprecated APIs.

**To Reproduce**
Create a new project and follow the documentation linked above.
The code in question:
```
GHAppInstallation appInstallation = gitHubApp.getApp().getInstallationById(111111);
```
Where the call to `getApp()` and `getInstallationById(...)` are both marked as deprecated without listing what should be used instead.

**Expected behavior**
- The official documentation should not make use of deprecated APIs.
- The JavaDoc should point you to what should be used instead.

**Comment by timja** [comment]
It's a weird way that this library works, anything that is classed as a preview feature by GitHub is marked as deprecated. So that you don't use preview apis without being aware...
