### ISSUE TITLE
Add @JsonIgnore for conflicting setters

### ISSUE THREAD

**Issue by JKalash** [hub4j/github-api#971]
**Describe the bug**
I am trying to deserialize a payload body into a corresponding `GHEventPayload` subclass as such:
`mapper.readValue(payloadBytes, GHEventPayload.IssueComment.class);`

 but am getting the following json mapping exception:
```
com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "assignees": org.kohsuke.github.GHIssue#setAssignees(1 params) vs org.kohsuke.github.GHIssue#setAssignees
```

**To Reproduce**
Attempt to deserialise any GH webhook payload into a GHEventPayload via Jacjson Object Mapper

**Expected behavior**
Should deserialise into the expected class but Jackson exeption thrown

**Desktop (please complete the following information):**
N/A

**Additional context**
In this example the assignees field was an empty array. Wondering if there are other field setters that may potentially need a `@JsonIgnore` or perhaps another way to deal with this?

**Comment by seregamorph** [comment]
Probably you use your own `ObjectMapper` instance. Instead you should use this:
```java
GitHub.offline().parseEventPayload(StringReader(payload), GHEventPayload.IssueComment.class)
```
if you still want to use your own ObjectMapper, create a separate instance (do not inject standard from the context) and setup it this way:
```
    private static final ObjectMapper MAPPER = new ObjectMapper();
    static {
        MAPPER.setVisibility(new VisibilityChecker.Std(NONE, NONE, NONE, NONE, ANY));
        MAPPER.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        MAPPER.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true);
        MAPPER.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
    }
```
(you can find this code in `org.kohsuke.github.GitHubClient`)

**Comment by bitwiseman** [comment]
@JKalash  Does that address your concern?
