### ISSUE TITLE
Stuck when `builder.withOAuthToken(token)`

### ISSUE THREAD

**Issue by roeniss** [hub4j/github-api#987]
**Describe the bug**
Below codes don't throw any exception but stuck forever. (at least, 10 minutes) I think we should make timeout handling, assertNotNull, or etc.

**To Reproduce**

(I'm using Junit5)

```java
class GithubClientTest {
  // ...
  @BeforeEach 
  void setUp() {
    String token = null;
    this.dashboard = new GithubClient(token); // this line not gonna end.
  }
  // ... 
```

**Expected behavior**
A clear and concise description of what you expected to happen:
timeout, or just excepetion.

**Desktop (please complete the following information):**
```bash
❯❯❯ neofetch
                    'c.          roeniss@MacBook-Pro.local
                 ,xNMM.          -----------------------
               .OMMMMo           OS: macOS Catalina 10.15.6 19G2021 x86_64
               OMMM0,            Host: MacBookPro16,1
     .;loddo:' loolloddol;.      Kernel: 19.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 7 days, 6 hours, 58 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 159 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.7.1
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 2560x1440@2x, 1792x1120@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Yellow (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: MesloLGS-NF-Regular 14
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Intel i9-9980HK (16) @ 2.40GHz
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Intel UHD Graphics 630, AMD Radeon Pro 5300M
       .cooc,.    .,coo:.        Memory: 20585MiB / 32768MiB
```
and github-api-1.117.jar.

**Comment by bitwiseman** [comment]
`GitHubClient` is an internal class with an internal constructor.  How are you even doing this?

**Comment by roeniss** [comment]
@bitwiseman First, I'm sorry to have caused you a misunderstanding. That `GithubClient` is my custom class for handling `GitHub` class.

Second, currently I can not reproduce that situation again. Maybe some of my IntelliJ settings were wrong and (without my noticing) resolved. I think we can close this now.
